var nodes_data = [
	{"name": "A0", "type": 0},
	{"name": "E1", "type": 0},
	{"name": "A1", "type": 0},
	{"name": "E2", "type": 0},
	{"name": "A2", "type": 0},
	{"name": "E3", "type": 2},
	{"name": "A3", "type": 0},
	{"name": "E4", "type": 0},
	{"name": "C4", "type": 0},
	{"name": "C5", "type": 0},
	{"name": "C6", "type": 0},
	{"name": "C7", "type": 0},
	{"name": "end", "type": 2},
	{"name": "B0", "type": 0},
	{"name": "B1", "type": 0},
	{"name": "D2", "type": 0},
	{"name": "B2", "type": 0},
	{"name": "start", "type": 1},
	{"name": "D3", "type": 0},
	{"name": "B3", "type": 0},
	{"name": "D4", "type": 0},
	{"name": "D5", "type": 0},
]

var links_data = [
	{"source": "A0", "target": "A1"},
	{"source": "A0", "target": "E1"},
	{"source": "E1", "target": "E2"},
	{"source": "E1", "target": "A0"},
	{"source": "A1", "target": "D2"},
	{"source": "A1", "target": "A2"},
	{"source": "A1", "target": "A0"},
	{"source": "E2", "target": "E3"},
	{"source": "E2", "target": "E1"},
	{"source": "A2", "target": "A3"},
	{"source": "A2", "target": "A1"},
	{"source": "E3", "target": "E4"},
	{"source": "E3", "target": "E2"},
	{"source": "A3", "target": "end"},
	{"source": "A3", "target": "B3"},
	{"source": "A3", "target": "A2"},
	{"source": "E4", "target": "end"},
	{"source": "E4", "target": "E3"},
	{"source": "C4", "target": "C5"},
	{"source": "C4", "target": "B3"},
	{"source": "C5", "target": "C6"},
	{"source": "C5", "target": "C4"},
	{"source": "C6", "target": "C7"},
	{"source": "C6", "target": "C5"},
	{"source": "C7", "target": "end"},
	{"source": "C7", "target": "C6"},
	{"source": "end", "target": "E4"},
	{"source": "end", "target": "D5"},
	{"source": "end", "target": "C7"},
	{"source": "end", "target": "A3"},
	{"source": "B0", "target": "B1"},
	{"source": "B1", "target": "B2"},
	{"source": "B1", "target": "B0"},
	{"source": "D2", "target": "D3"},
	{"source": "D2", "target": "A1"},
	{"source": "B2", "target": "B3"},
	{"source": "B2", "target": "B1"},
	{"source": "start", "target": "B0"},
	{"source": "start", "target": "A0"},
	{"source": "D3", "target": "D4"},
	{"source": "D3", "target": "D2"},
	{"source": "B3", "target": "C4"},
	{"source": "B3", "target": "A3"},
	{"source": "B3", "target": "B2"},
	{"source": "D4", "target": "D5"},
	{"source": "D4", "target": "D3"},
	{"source": "D5", "target": "end"},
	{"source": "D5", "target": "D4"},
]


var turns_data = [
	[
		{"source": "start", "target": "B0", "num": 1},
		{"source": "start", "target": "A0", "num": 2},
	],
	[
		{"source": "B0", "target": "B1", "num": 1},
		{"source": "A0", "target": "E1", "num": 2},
		{"source": "start", "target": "B0", "num": 3},
		{"source": "start", "target": "A0", "num": 4},
	],
	[
		{"source": "B1", "target": "B2", "num": 1},
		{"source": "E1", "target": "E2", "num": 2},
		{"source": "B0", "target": "B1", "num": 3},
		{"source": "A0", "target": "E1", "num": 4},
		{"source": "start", "target": "B0", "num": 5},
		{"source": "start", "target": "A0", "num": 6},
	],
	[
		{"source": "B2", "target": "B3", "num": 1},
		{"source": "E2", "target": "E3", "num": 2},
		{"source": "B1", "target": "B2", "num": 3},
		{"source": "E1", "target": "E2", "num": 4},
		{"source": "B0", "target": "B1", "num": 5},
		{"source": "A0", "target": "E1", "num": 6},
		{"source": "start", "target": "B0", "num": 7},
		{"source": "start", "target": "A0", "num": 8},
	],
	[
		{"source": "B3", "target": "A3", "num": 1},
		{"source": "B2", "target": "B3", "num": 3},
		{"source": "E2", "target": "E3", "num": 4},
		{"source": "B1", "target": "B2", "num": 5},
		{"source": "E1", "target": "E2", "num": 6},
		{"source": "B0", "target": "B1", "num": 7},
		{"source": "A0", "target": "E1", "num": 8},
		{"source": "start", "target": "A0", "num": 9},
	],
	[
		{"source": "A3", "target": "end", "num": 1},
		{"source": "B3", "target": "A3", "num": 3},
		{"source": "B2", "target": "B3", "num": 5},
		{"source": "E2", "target": "E3", "num": 6},
		{"source": "B1", "target": "B2", "num": 7},
		{"source": "E1", "target": "E2", "num": 8},
		{"source": "A0", "target": "E1", "num": 9},
		{"source": "start", "target": "A0", "num": 10},
	],
	[
		{"source": "A3", "target": "end", "num": 3},
		{"source": "B3", "target": "A3", "num": 5},
		{"source": "B2", "target": "B3", "num": 7},
		{"source": "E2", "target": "E3", "num": 8},
		{"source": "E1", "target": "E2", "num": 9},
		{"source": "A0", "target": "E1", "num": 10},
	],
	[
		{"source": "A3", "target": "end", "num": 5},
		{"source": "B3", "target": "A3", "num": 7},
		{"source": "E2", "target": "E3", "num": 9},
		{"source": "E1", "target": "E2", "num": 10},
	],
	[
		{"source": "A3", "target": "end", "num": 7},
		{"source": "E2", "target": "E3", "num": 10},
	]
]