var nodes_data = [
	{"name": "Bzo4", "type": 0},
	{"name": "Cxy0", "type": 0},
	{"name": "Dev3", "type": 0},
	{"name": "Fnf8", "type": 0},
	{"name": "Se_5", "type": 0},
	{"name": "Tnw2", "type": 0},
	{"name": "Vpy1", "type": 0},
	{"name": "Spm8", "type": 0},
	{"name": "Dfv1", "type": 0},
	{"name": "Quz9", "type": 0},
	{"name": "Hjz1", "type": 0},
	{"name": "Imb1", "type": 0},
	{"name": "Brq7", "type": 0},
	{"name": "Xuj4", "type": 0},
	{"name": "Bsq1", "type": 0},
	{"name": "Xpk8", "type": 0},
	{"name": "Aqh5", "type": 0},
	{"name": "Sdp4", "type": 0},
	{"name": "Mtv0", "type": 0},
	{"name": "Trf9", "type": 0},
	{"name": "Jtj9", "type": 0},
	{"name": "Gxn3", "type": 0},
	{"name": "Nas7", "type": 0},
	{"name": "Qyz1", "type": 0},
	{"name": "Hth4", "type": 0},
	{"name": "G_c7", "type": 0},
	{"name": "Tzu9", "type": 0},
	{"name": "Ppb7", "type": 0},
	{"name": "D_x9", "type": 0},
	{"name": "Hbl2", "type": 0},
	{"name": "Exl0", "type": 0},
	{"name": "Ttf9", "type": 0},
	{"name": "Div8", "type": 0},
	{"name": "Jim3", "type": 0},
	{"name": "Dle9", "type": 0},
	{"name": "X__7", "type": 0},
	{"name": "Mfi7", "type": 0},
	{"name": "Fzu6", "type": 0},
	{"name": "Gt_2", "type": 0},
	{"name": "Eh_7", "type": 0},
	{"name": "Agk3", "type": 0},
	{"name": "Wxa1", "type": 0},
	{"name": "Pxq8", "type": 0},
	{"name": "B_v6", "type": 0},
	{"name": "N_t9", "type": 0},
	{"name": "Rfg7", "type": 0},
	{"name": "Dgw1", "type": 0},
	{"name": "T_k3", "type": 0},
	{"name": "Elo0", "type": 0},
	{"name": "Fbj4", "type": 0},
	{"name": "Cyz9", "type": 0},
	{"name": "Vvy2", "type": 0},
	{"name": "Rgg3", "type": 0},
	{"name": "Cen5", "type": 0},
	{"name": "Ujr8", "type": 0},
	{"name": "Cxj5", "type": 0},
	{"name": "Dgw5", "type": 0},
	{"name": "Fze5", "type": 0},
	{"name": "Pbv8", "type": 0},
	{"name": "Qhn1", "type": 0},
	{"name": "C__7", "type": 0},
	{"name": "Amj8", "type": 0},
	{"name": "Mnh0", "type": 0},
	{"name": "Fhi4", "type": 0},
	{"name": "Zpo1", "type": 0},
	{"name": "Okk4", "type": 0},
	{"name": "Yby1", "type": 0},
	{"name": "Zn_4", "type": 0},
	{"name": "Wwr9", "type": 0},
	{"name": "Orz5", "type": 0},
	{"name": "Gyo4", "type": 0},
	{"name": "Itb6", "type": 0},
	{"name": "Nx_6", "type": 0},
	{"name": "Zvn0", "type": 0},
	{"name": "Bjd7", "type": 0},
	{"name": "Dwt9", "type": 0},
	{"name": "Gx_4", "type": 0},
	{"name": "Wyr3", "type": 0},
	{"name": "N_u2", "type": 0},
	{"name": "Rby8", "type": 0},
	{"name": "Gy_1", "type": 0},
	{"name": "O_n5", "type": 0},
	{"name": "Qtl4", "type": 0},
	{"name": "Rpf0", "type": 0},
	{"name": "Jd_0", "type": 0},
	{"name": "Pwb5", "type": 0},
	{"name": "T_l2", "type": 0},
	{"name": "Pie5", "type": 0},
	{"name": "Ahl6", "type": 0},
	{"name": "Bxr6", "type": 0},
	{"name": "Cd_2", "type": 0},
	{"name": "Idf8", "type": 0},
	{"name": "Gwp7", "type": 0},
	{"name": "Vwz0", "type": 0},
	{"name": "Nsq9", "type": 0},
	{"name": "W_x4", "type": 0},
	{"name": "Xwl1", "type": 0},
	{"name": "Myw1", "type": 0},
	{"name": "Pje9", "type": 0},
	{"name": "Zr_5", "type": 0},
	{"name": "B_g8", "type": 0},
	{"name": "Hxi7", "type": 0},
	{"name": "Icw5", "type": 0},
	{"name": "Blu3", "type": 0},
	{"name": "Tvx6", "type": 0},
	{"name": "Cqm4", "type": 0},
	{"name": "Gsa4", "type": 0},
	{"name": "Ibg4", "type": 0},
	{"name": "D_j1", "type": 0},
	{"name": "Nrr0", "type": 0},
	{"name": "J_q8", "type": 0},
	{"name": "Ged9", "type": 0},
	{"name": "D_j9", "type": 0},
	{"name": "Ggd0", "type": 0},
	{"name": "Vsk8", "type": 0},
	{"name": "Aml0", "type": 0},
	{"name": "Neu3", "type": 0},
	{"name": "Kaj7", "type": 0},
	{"name": "Dlx5", "type": 0},
	{"name": "X_r4", "type": 0},
	{"name": "Kkh8", "type": 0},
	{"name": "Twh9", "type": 0},
	{"name": "Yky0", "type": 0},
	{"name": "Ppe0", "type": 0},
	{"name": "Aim7", "type": 0},
	{"name": "Kdz9", "type": 0},
	{"name": "Ela0", "type": 0},
	{"name": "Fwh9", "type": 0},
	{"name": "Fik8", "type": 0},
	{"name": "Mkk2", "type": 0},
	{"name": "Pmf1", "type": 0},
	{"name": "Hbo7", "type": 0},
	{"name": "Kdj7", "type": 0},
	{"name": "Spq8", "type": 0},
	{"name": "Z_u2", "type": 0},
	{"name": "Glt5", "type": 0},
	{"name": "Ggu8", "type": 0},
	{"name": "Ob_6", "type": 0},
	{"name": "Vnm8", "type": 0},
	{"name": "Oc_2", "type": 0},
	{"name": "Zjs0", "type": 0},
	{"name": "Nss6", "type": 0},
	{"name": "Eup7", "type": 0},
	{"name": "Krx1", "type": 0},
	{"name": "Zdd0", "type": 0},
	{"name": "Cm_6", "type": 0},
	{"name": "Bxt9", "type": 0},
	{"name": "Yjz7", "type": 0},
	{"name": "Q_s0", "type": 0},
	{"name": "Nku2", "type": 0},
	{"name": "Ac_0", "type": 0},
	{"name": "Zdd4", "type": 0},
	{"name": "Dak7", "type": 0},
	{"name": "Zpr0", "type": 0},
	{"name": "Y_l8", "type": 0},
	{"name": "Rdk2", "type": 0},
	{"name": "Gvb9", "type": 0},
	{"name": "Wzd6", "type": 0},
	{"name": "Bgx2", "type": 0},
	{"name": "Ryw2", "type": 0},
	{"name": "V_q1", "type": 0},
	{"name": "J_s4", "type": 0},
	{"name": "Ibi4", "type": 0},
	{"name": "Suq5", "type": 0},
	{"name": "Sob4", "type": 0},
	{"name": "Gmu1", "type": 0},
	{"name": "Bci0", "type": 0},
	{"name": "I_j1", "type": 0},
	{"name": "Wkx9", "type": 0},
	{"name": "Rfk5", "type": 0},
	{"name": "Kux7", "type": 0},
	{"name": "Xgr8", "type": 0},
	{"name": "Urd4", "type": 0},
	{"name": "Doi2", "type": 0},
	{"name": "Onn9", "type": 0},
	{"name": "Vtm7", "type": 0},
	{"name": "T_o9", "type": 0},
	{"name": "Pxe6", "type": 0},
	{"name": "Ydl0", "type": 0},
	{"name": "Bkx1", "type": 0},
	{"name": "Ubx4", "type": 0},
	{"name": "Bjx9", "type": 0},
	{"name": "Shd2", "type": 0},
	{"name": "Zmc7", "type": 0},
	{"name": "Ofp4", "type": 0},
	{"name": "Mml9", "type": 0},
	{"name": "Msk1", "type": 0},
	{"name": "Oaq8", "type": 0},
	{"name": "Ah_0", "type": 0},
	{"name": "Qt_8", "type": 0},
	{"name": "Uoe5", "type": 0},
	{"name": "Ynj6", "type": 0},
	{"name": "Q_t6", "type": 0},
	{"name": "H_a7", "type": 0},
	{"name": "Zjd3", "type": 0},
	{"name": "Xhb4", "type": 0},
	{"name": "Ruy0", "type": 0},
	{"name": "Ivv7", "type": 0},
	{"name": "Fen4", "type": 0},
	{"name": "Geg5", "type": 0},
	{"name": "Unv1", "type": 0},
	{"name": "Zqs7", "type": 0},
	{"name": "Esr9", "type": 0},
	{"name": "Qw_3", "type": 0},
	{"name": "Cgb8", "type": 0},
	{"name": "Wyf1", "type": 0},
	{"name": "V_b6", "type": 0},
	{"name": "Qpq7", "type": 0},
	{"name": "Jdc6", "type": 0},
	{"name": "Pky9", "type": 0},
	{"name": "Njw4", "type": 0},
	{"name": "Qjb5", "type": 0},
	{"name": "Bii2", "type": 0},
	{"name": "Uzt1", "type": 0},
	{"name": "Gvd4", "type": 0},
	{"name": "Izv3", "type": 0},
	{"name": "Bwf5", "type": 0},
	{"name": "Oym3", "type": 0},
	{"name": "Cbt0", "type": 0},
	{"name": "Qfc4", "type": 0},
	{"name": "Teo8", "type": 0},
	{"name": "Teo9", "type": 0},
	{"name": "Vgq8", "type": 0},
	{"name": "K_n0", "type": 0},
	{"name": "Khl3", "type": 0},
	{"name": "Xhc2", "type": 0},
	{"name": "Sku2", "type": 0},
	{"name": "Irx2", "type": 0},
	{"name": "Jy_6", "type": 0},
	{"name": "Zod2", "type": 0},
	{"name": "Bak4", "type": 0},
	{"name": "J_u4", "type": 0},
	{"name": "Te_1", "type": 0},
	{"name": "Ssc3", "type": 0},
	{"name": "Xks1", "type": 0},
	{"name": "Wij2", "type": 0},
	{"name": "Myk3", "type": 0},
	{"name": "Md_6", "type": 0},
	{"name": "Qdd1", "type": 0},
	{"name": "Qsq8", "type": 0},
	{"name": "Sff1", "type": 0},
	{"name": "Gyd1", "type": 0},
	{"name": "Jhc2", "type": 0},
	{"name": "Yzi0", "type": 0},
	{"name": "Jis8", "type": 0},
	{"name": "Hp_1", "type": 0},
	{"name": "Uix9", "type": 0},
	{"name": "Ivg6", "type": 0},
	{"name": "Hmp4", "type": 0},
	{"name": "Vr_1", "type": 0},
	{"name": "Woi3", "type": 0},
	{"name": "Pwg7", "type": 0},
	{"name": "Egv2", "type": 0},
	{"name": "I_l5", "type": 0},
	{"name": "Ney2", "type": 0},
	{"name": "Eod3", "type": 0},
	{"name": "Hnp4", "type": 0},
	{"name": "Mf_8", "type": 0},
	{"name": "Rqk3", "type": 0},
	{"name": "Gmg2", "type": 0},
	{"name": "C_e9", "type": 0},
	{"name": "N_j8", "type": 0},
	{"name": "G_j3", "type": 0},
	{"name": "Nuv0", "type": 0},
	{"name": "Xce5", "type": 0},
	{"name": "K_o7", "type": 0},
	{"name": "J_v7", "type": 0},
	{"name": "Jit5", "type": 0},
	{"name": "Qfu0", "type": 0},
	{"name": "Bmz5", "type": 0},
	{"name": "Hgr7", "type": 0},
	{"name": "Gei8", "type": 0},
	{"name": "P_m4", "type": 0},
	{"name": "Tj_9", "type": 0},
	{"name": "Q_f8", "type": 0},
	{"name": "At_4", "type": 0},
	{"name": "Xvr2", "type": 0},
	{"name": "D__0", "type": 0},
	{"name": "Jyq2", "type": 0},
	{"name": "Slf2", "type": 0},
	{"name": "Vtp6", "type": 0},
	{"name": "Vib6", "type": 0},
	{"name": "Qxa8", "type": 0},
	{"name": "Pkk2", "type": 0},
	{"name": "Z_i7", "type": 0},
	{"name": "Wlk2", "type": 0},
	{"name": "Zdh5", "type": 0},
	{"name": "Aes1", "type": 0},
	{"name": "Av_1", "type": 0},
	{"name": "Ugz8", "type": 0},
	{"name": "A_d1", "type": 0},
	{"name": "Vy_2", "type": 0},
	{"name": "Pvi0", "type": 0},
	{"name": "Jkd5", "type": 0},
	{"name": "Hx_1", "type": 0},
	{"name": "Plk6", "type": 0},
	{"name": "Uyf7", "type": 0},
	{"name": "Xju7", "type": 0},
	{"name": "Qss4", "type": 0},
	{"name": "Mm_8", "type": 0},
	{"name": "Okb2", "type": 0},
	{"name": "Da_7", "type": 0},
	{"name": "Nyf5", "type": 0},
	{"name": "F_b3", "type": 0},
	{"name": "Mn_4", "type": 0},
	{"name": "Vlb4", "type": 0},
	{"name": "Oz_3", "type": 0},
	{"name": "Vjs2", "type": 0},
	{"name": "Xef4", "type": 0},
	{"name": "Pnk3", "type": 0},
	{"name": "Fn_4", "type": 0},
	{"name": "Mfa0", "type": 0},
	{"name": "Imk5", "type": 0},
	{"name": "Bqj5", "type": 0},
	{"name": "Hz_1", "type": 0},
	{"name": "Xod9", "type": 0},
	{"name": "Ter1", "type": 0},
	{"name": "N_l5", "type": 0},
	{"name": "Fo_7", "type": 0},
	{"name": "Oau8", "type": 0},
	{"name": "F_s4", "type": 0},
	{"name": "Kzk7", "type": 0},
	{"name": "Rwl1", "type": 0},
	{"name": "Xnu9", "type": 0},
	{"name": "Eci4", "type": 0},
	{"name": "Quc9", "type": 0},
	{"name": "Zog4", "type": 0},
	{"name": "Hgt4", "type": 0},
	{"name": "Pcn6", "type": 0},
	{"name": "Kep0", "type": 0},
	{"name": "Wrk8", "type": 0},
	{"name": "Wjm0", "type": 0},
	{"name": "Tka0", "type": 0},
	{"name": "Ddp4", "type": 0},
	{"name": "Gjj9", "type": 0},
	{"name": "Yi_9", "type": 0},
	{"name": "Hpb4", "type": 0},
	{"name": "Mhr1", "type": 0},
	{"name": "Fs_5", "type": 0},
	{"name": "H_v6", "type": 0},
	{"name": "Xhw2", "type": 0},
	{"name": "Mds0", "type": 0},
	{"name": "Rcq1", "type": 0},
	{"name": "Cfw2", "type": 0},
	{"name": "Nvh8", "type": 0},
	{"name": "Xmv7", "type": 0},
	{"name": "S_k1", "type": 0},
	{"name": "Vee6", "type": 0},
	{"name": "Csd4", "type": 0},
	{"name": "F_t5", "type": 0},
	{"name": "Ujk6", "type": 0},
	{"name": "F_t6", "type": 0},
	{"name": "Joe7", "type": 0},
	{"name": "Noj1", "type": 0},
	{"name": "Aqb8", "type": 0},
	{"name": "Jlf0", "type": 0},
	{"name": "Jfg9", "type": 0},
	{"name": "Vrs5", "type": 0},
	{"name": "Wb_6", "type": 0},
	{"name": "Qjw3", "type": 0},
	{"name": "Dhp5", "type": 0},
	{"name": "Nkk3", "type": 0},
	{"name": "Gzx5", "type": 0},
	{"name": "Ilm5", "type": 0},
	{"name": "Jsu2", "type": 0},
	{"name": "Ucm1", "type": 0},
	{"name": "Sak2", "type": 0},
	{"name": "Zyf8", "type": 0},
	{"name": "Vju2", "type": 0},
	{"name": "Iwk0", "type": 0},
	{"name": "Nrz8", "type": 0},
	{"name": "Hqs9", "type": 0},
	{"name": "Aee8", "type": 0},
	{"name": "Zjz0", "type": 0},
	{"name": "Blm8", "type": 0},
	{"name": "Xjg8", "type": 0},
	{"name": "Rea6", "type": 0},
	{"name": "Qlw5", "type": 0},
	{"name": "Aza1", "type": 0},
	{"name": "Cnf1", "type": 0},
	{"name": "Hju3", "type": 0},
	{"name": "Glk9", "type": 0},
	{"name": "Zkz1", "type": 0},
	{"name": "Eoh8", "type": 0},
	{"name": "Qrv0", "type": 0},
	{"name": "N_n9", "type": 0},
	{"name": "Ald5", "type": 0},
	{"name": "Qfh7", "type": 0},
	{"name": "Emy6", "type": 0},
	{"name": "Opt4", "type": 0},
	{"name": "Pd_9", "type": 0},
	{"name": "Wmn5", "type": 0},
	{"name": "Kvn9", "type": 0},
	{"name": "A_g6", "type": 0},
	{"name": "C_z0", "type": 0},
	{"name": "Jpf7", "type": 0},
	{"name": "V_x7", "type": 0},
	{"name": "Opd1", "type": 0},
	{"name": "Nyi4", "type": 0},
	{"name": "Jix5", "type": 0},
	{"name": "Zry0", "type": 0},
	{"name": "Mbu4", "type": 0},
	{"name": "Uhm2", "type": 0},
	{"name": "Rkq2", "type": 0},
	{"name": "Xog0", "type": 0},
	{"name": "P_q7", "type": 0},
	{"name": "Mbu7", "type": 0},
	{"name": "Cqf4", "type": 0},
	{"name": "Fqr0", "type": 0},
	{"name": "Jfy4", "type": 0},
	{"name": "Xqw5", "type": 0},
	{"name": "Qei5", "type": 0},
	{"name": "Wfp4", "type": 0},
	{"name": "Avs7", "type": 0},
	{"name": "Vpu2", "type": 0},
	{"name": "Auc2", "type": 0},
	{"name": "Zsy7", "type": 0},
	{"name": "Nrk3", "type": 0},
	{"name": "Suh9", "type": 0},
	{"name": "Das7", "type": 0},
	{"name": "Qjh9", "type": 0},
	{"name": "Hax2", "type": 0},
	{"name": "Bxl1", "type": 0},
	{"name": "Cpw4", "type": 0},
	{"name": "S_m5", "type": 0},
	{"name": "Avc4", "type": 0},
	{"name": "Ajv2", "type": 0},
	{"name": "Swh3", "type": 0},
	{"name": "Yma1", "type": 0},
	{"name": "Avc6", "type": 0},
	{"name": "H_h8", "type": 0},
	{"name": "Vhw3", "type": 0},
	{"name": "Deb7", "type": 0},
	{"name": "Mmc3", "type": 0},
	{"name": "Sdl6", "type": 0},
	{"name": "Aou3", "type": 0},
	{"name": "Wmo3", "type": 0},
	{"name": "Bh_7", "type": 0},
	{"name": "Wk_4", "type": 0},
	{"name": "Vvt7", "type": 0},
	{"name": "Att4", "type": 0},
	{"name": "Ugn1", "type": 0},
	{"name": "Sty9", "type": 0},
	{"name": "Xhi7", "type": 0},
	{"name": "Zuy9", "type": 0},
	{"name": "Xky1", "type": 0},
	{"name": "Aeg0", "type": 0},
	{"name": "Awc6", "type": 0},
	{"name": "Yw_5", "type": 0},
	{"name": "Gjm7", "type": 0},
	{"name": "Bko7", "type": 0},
	{"name": "Rw_2", "type": 0},
	{"name": "Qjy7", "type": 0},
	{"name": "Jez4", "type": 0},
	{"name": "Obh6", "type": 0},
	{"name": "Ngn7", "type": 0},
	{"name": "Tfe8", "type": 0},
	{"name": "Pxm2", "type": 0},
	{"name": "Hzc5", "type": 0},
	{"name": "Rpq8", "type": 0},
	{"name": "Isn1", "type": 0},
	{"name": "U_p9", "type": 0},
	{"name": "Gco2", "type": 0},
	{"name": "Vtu8", "type": 0},
	{"name": "Uxk0", "type": 0},
	{"name": "Rec8", "type": 0},
	{"name": "Tvb2", "type": 0},
	{"name": "Yrq3", "type": 0},
	{"name": "Vig8", "type": 0},
	{"name": "Wlp1", "type": 0},
	{"name": "Hsu7", "type": 0},
	{"name": "Kpq8", "type": 0},
	{"name": "Im_4", "type": 0},
	{"name": "Ida1", "type": 0},
	{"name": "Mss3", "type": 0},
	{"name": "Mev3", "type": 0},
	{"name": "Grl5", "type": 0},
	{"name": "Tyr3", "type": 0},
	{"name": "Itn8", "type": 0},
	{"name": "Po_5", "type": 0},
	{"name": "Qyw1", "type": 0},
	{"name": "Tdw2", "type": 0},
	{"name": "Aai6", "type": 0},
	{"name": "Jij2", "type": 0},
	{"name": "Bqo7", "type": 0},
	{"name": "Ndp0", "type": 0},
	{"name": "Xal9", "type": 0},
	{"name": "Kft9", "type": 0},
	{"name": "B_s6", "type": 0},
	{"name": "Bro5", "type": 0},
	{"name": "Wkq7", "type": 0},
	{"name": "Pdb4", "type": 0},
	{"name": "N_q9", "type": 0},
	{"name": "Rrr1", "type": 0},
	{"name": "Jfk1", "type": 0},
	{"name": "Rrr3", "type": 0},
	{"name": "B_c0", "type": 0},
	{"name": "Oih9", "type": 0},
	{"name": "G_q7", "type": 0},
	{"name": "Ouv4", "type": 0},
	{"name": "Tfw4", "type": 0},
	{"name": "Dqr2", "type": 0},
	{"name": "Mtt0", "type": 0},
	{"name": "Gg_6", "type": 0},
	{"name": "Jqy9", "type": 0},
	{"name": "D_v0", "type": 0},
	{"name": "Kkc9", "type": 0},
	{"name": "Ovv4", "type": 0},
	{"name": "Hzu3", "type": 0},
	{"name": "Omx3", "type": 0},
	{"name": "Aih7", "type": 0},
	{"name": "Kxq0", "type": 0},
	{"name": "Aei7", "type": 0},
	{"name": "Zco2", "type": 0},
	{"name": "Uip0", "type": 0},
	{"name": "Thw9", "type": 0},
	{"name": "Bqp8", "type": 2},
	{"name": "Hbj8", "type": 0},
	{"name": "Ksb1", "type": 0},
	{"name": "Ndq1", "type": 0},
	{"name": "Mfg7", "type": 0},
	{"name": "W_d9", "type": 0},
	{"name": "Fzs7", "type": 0},
	{"name": "Dmc7", "type": 0},
	{"name": "Ojy9", "type": 1},
	{"name": "Yrs7", "type": 0},
	{"name": "Xwy7", "type": 0},
	{"name": "Ies9", "type": 0},
	{"name": "Vej9", "type": 0},
	{"name": "Avf5", "type": 0},
	{"name": "Dur5", "type": 0},
	{"name": "Ouw5", "type": 0},
	{"name": "Snm1", "type": 0},
	{"name": "U_b7", "type": 0},
	{"name": "Tre6", "type": 0},
	{"name": "Jti8", "type": 0},
	{"name": "Rcf2", "type": 0},
	{"name": "Px_8", "type": 0},
	{"name": "Pkb1", "type": 0},
	{"name": "Mdh5", "type": 0},
	{"name": "Ulp3", "type": 0},
]

var links_data = [
	{"source": "Bzo4", "target": "Pwg7"},
	{"source": "Bzo4", "target": "Xmv7"},
	{"source": "Cxy0", "target": "Nrr0"},
	{"source": "Cxy0", "target": "Bko7"},
	{"source": "Dev3", "target": "Bii2"},
	{"source": "Dev3", "target": "Qrv0"},
	{"source": "Fnf8", "target": "Gt_2"},
	{"source": "Fnf8", "target": "Po_5"},
	{"source": "Se_5", "target": "Zdd0"},
	{"source": "Se_5", "target": "Gxn3"},
	{"source": "Tnw2", "target": "Xgr8"},
	{"source": "Tnw2", "target": "Uoe5"},
	{"source": "Vpy1", "target": "Rea6"},
	{"source": "Vpy1", "target": "Msk1"},
	{"source": "Spm8", "target": "J_s4"},
	{"source": "Spm8", "target": "Ssc3"},
	{"source": "Dfv1", "target": "Jfk1"},
	{"source": "Dfv1", "target": "Eh_7"},
	{"source": "Quz9", "target": "Hgr7"},
	{"source": "Quz9", "target": "Mkk2"},
	{"source": "Hjz1", "target": "Trf9"},
	{"source": "Hjz1", "target": "Qhn1"},
	{"source": "Imb1", "target": "Pwg7"},
	{"source": "Brq7", "target": "Mml9"},
	{"source": "Brq7", "target": "Unv1"},
	{"source": "Xuj4", "target": "Sty9"},
	{"source": "Bsq1", "target": "Glt5"},
	{"source": "Bsq1", "target": "Zsy7"},
	{"source": "Xpk8", "target": "Pd_9"},
	{"source": "Aqh5", "target": "Hsu7"},
	{"source": "Aqh5", "target": "Sdl6"},
	{"source": "Sdp4", "target": "Elo0"},
	{"source": "Sdp4", "target": "Fqr0"},
	{"source": "Mtv0", "target": "Zqs7"},
	{"source": "Mtv0", "target": "Jhc2"},
	{"source": "Trf9", "target": "J_q8"},
	{"source": "Trf9", "target": "Hjz1"},
	{"source": "Jtj9", "target": "Tzu9"},
	{"source": "Jtj9", "target": "Fo_7"},
	{"source": "Gxn3", "target": "Se_5"},
	{"source": "Gxn3", "target": "Blm8"},
	{"source": "Nas7", "target": "X__7"},
	{"source": "Nas7", "target": "Rfk5"},
	{"source": "Qyz1", "target": "Agk3"},
	{"source": "Qyz1", "target": "Wyf1"},
	{"source": "Hth4", "target": "Jfk1"},
	{"source": "Hth4", "target": "Qfc4"},
	{"source": "G_c7", "target": "U_p9"},
	{"source": "G_c7", "target": "Aei7"},
	{"source": "Tzu9", "target": "Yrs7"},
	{"source": "Tzu9", "target": "Jtj9"},
	{"source": "Ppb7", "target": "Jyq2"},
	{"source": "Ppb7", "target": "Wij2"},
	{"source": "D_x9", "target": "Gco2"},
	{"source": "D_x9", "target": "Bqp8"},
	{"source": "Hbl2", "target": "Mbu7"},
	{"source": "Hbl2", "target": "V_x7"},
	{"source": "Exl0", "target": "Jez4"},
	{"source": "Exl0", "target": "Ggd0"},
	{"source": "Ttf9", "target": "V_q1"},
	{"source": "Ttf9", "target": "Tfe8"},
	{"source": "Div8", "target": "Xju7"},
	{"source": "Div8", "target": "Z_u2"},
	{"source": "Jim3", "target": "Jhc2"},
	{"source": "Jim3", "target": "Rw_2"},
	{"source": "Dle9", "target": "Avs7"},
	{"source": "Dle9", "target": "Wxa1"},
	{"source": "X__7", "target": "Nku2"},
	{"source": "X__7", "target": "Kkh8"},
	{"source": "X__7", "target": "Nas7"},
	{"source": "Mfi7", "target": "Cm_6"},
	{"source": "Mfi7", "target": "Hx_1"},
	{"source": "Fzu6", "target": "Qfh7"},
	{"source": "Fzu6", "target": "Uip0"},
	{"source": "Fzu6", "target": "Vee6"},
	{"source": "Gt_2", "target": "Yzi0"},
	{"source": "Gt_2", "target": "Fnf8"},
	{"source": "Eh_7", "target": "Orz5"},
	{"source": "Eh_7", "target": "Dfv1"},
	{"source": "Agk3", "target": "Qyz1"},
	{"source": "Agk3", "target": "Ah_0"},
	{"source": "Wxa1", "target": "Rcf2"},
	{"source": "Wxa1", "target": "Dle9"},
	{"source": "Pxq8", "target": "Hgt4"},
	{"source": "Pxq8", "target": "Vpu2"},
	{"source": "B_v6", "target": "Jdc6"},
	{"source": "B_v6", "target": "Mnh0"},
	{"source": "N_t9", "target": "Xwy7"},
	{"source": "N_t9", "target": "Sff1"},
	{"source": "N_t9", "target": "Pmf1"},
	{"source": "Rfg7", "target": "Bmz5"},
	{"source": "Rfg7", "target": "Icw5"},
	{"source": "Dgw1", "target": "U_p9"},
	{"source": "Dgw1", "target": "Ppe0"},
	{"source": "T_k3", "target": "Bh_7"},
	{"source": "Elo0", "target": "Dlx5"},
	{"source": "Elo0", "target": "Sdp4"},
	{"source": "Fbj4", "target": "Ouw5"},
	{"source": "Fbj4", "target": "Bqp8"},
	{"source": "Cyz9", "target": "Oz_3"},
	{"source": "Cyz9", "target": "Wmo3"},
	{"source": "Vvy2", "target": "Gjm7"},
	{"source": "Vvy2", "target": "Zkz1"},
	{"source": "Rgg3", "target": "Ucm1"},
	{"source": "Rgg3", "target": "Cpw4"},
	{"source": "Cen5", "target": "Vee6"},
	{"source": "Cen5", "target": "Rfk5"},
	{"source": "Ujr8", "target": "Ovv4"},
	{"source": "Ujr8", "target": "Bkx1"},
	{"source": "Cxj5", "target": "Jti8"},
	{"source": "Cxj5", "target": "Itb6"},
	{"source": "Cxj5", "target": "Njw4"},
	{"source": "Dgw5", "target": "Oc_2"},
	{"source": "Dgw5", "target": "Ndp0"},
	{"source": "Fze5", "target": "Thw9"},
	{"source": "Fze5", "target": "P_m4"},
	{"source": "Pbv8", "target": "Avc6"},
	{"source": "Pbv8", "target": "W_x4"},
	{"source": "Qhn1", "target": "Hjz1"},
	{"source": "Qhn1", "target": "Pnk3"},
	{"source": "C__7", "target": "Avc4"},
	{"source": "C__7", "target": "Wb_6"},
	{"source": "C__7", "target": "N_u2"},
	{"source": "Amj8", "target": "Bqj5"},
	{"source": "Amj8", "target": "Teo8"},
	{"source": "Mnh0", "target": "B_v6"},
	{"source": "Fhi4", "target": "Uhm2"},
	{"source": "Fhi4", "target": "Sob4"},
	{"source": "Zpo1", "target": "Cpw4"},
	{"source": "Zpo1", "target": "Hbo7"},
	{"source": "Okk4", "target": "Gjm7"},
	{"source": "Okk4", "target": "Wwr9"},
	{"source": "Yby1", "target": "Gjj9"},
	{"source": "Yby1", "target": "O_n5"},
	{"source": "Zn_4", "target": "Mev3"},
	{"source": "Zn_4", "target": "Tyr3"},
	{"source": "Wwr9", "target": "Ahl6"},
	{"source": "Wwr9", "target": "Ggu8"},
	{"source": "Wwr9", "target": "Okk4"},
	{"source": "Orz5", "target": "Eh_7"},
	{"source": "Orz5", "target": "Jix5"},
	{"source": "Gyo4", "target": "Jix5"},
	{"source": "Gyo4", "target": "N_j8"},
	{"source": "Itb6", "target": "Cxj5"},
	{"source": "Itb6", "target": "N_l5"},
	{"source": "Nx_6", "target": "Ajv2"},
	{"source": "Nx_6", "target": "Gyd1"},
	{"source": "Nx_6", "target": "Pdb4"},
	{"source": "Zvn0", "target": "Msk1"},
	{"source": "Bjd7", "target": "B_s6"},
	{"source": "Bjd7", "target": "Zjd3"},
	{"source": "Dwt9", "target": "Myk3"},
	{"source": "Gx_4", "target": "Isn1"},
	{"source": "Gx_4", "target": "Qjy7"},
	{"source": "Wyr3", "target": "Bxl1"},
	{"source": "Wyr3", "target": "Kvn9"},
	{"source": "Wyr3", "target": "Zog4"},
	{"source": "N_u2", "target": "C__7"},
	{"source": "Rby8", "target": "Z_i7"},
	{"source": "Rby8", "target": "Rrr1"},
	{"source": "Gy_1", "target": "Noj1"},
	{"source": "Gy_1", "target": "I_j1"},
	{"source": "O_n5", "target": "Yby1"},
	{"source": "O_n5", "target": "Jkd5"},
	{"source": "O_n5", "target": "Hp_1"},
	{"source": "Qtl4", "target": "Vib6"},
	{"source": "Qtl4", "target": "V_x7"},
	{"source": "Rpf0", "target": "V_b6"},
	{"source": "Rpf0", "target": "Kpq8"},
	{"source": "Jd_0", "target": "Sak2"},
	{"source": "Jd_0", "target": "Uyf7"},
	{"source": "Pwb5", "target": "Hx_1"},
	{"source": "Pwb5", "target": "Aai6"},
	{"source": "T_l2", "target": "Gvb9"},
	{"source": "T_l2", "target": "Ged9"},
	{"source": "Pie5", "target": "Ggd0"},
	{"source": "Pie5", "target": "Hbj8"},
	{"source": "Ahl6", "target": "Wwr9"},
	{"source": "Bxr6", "target": "Vgq8"},
	{"source": "Bxr6", "target": "Bqp8"},
	{"source": "Cd_2", "target": "Slf2"},
	{"source": "Idf8", "target": "Avs7"},
	{"source": "Gwp7", "target": "Plk6"},
	{"source": "Vwz0", "target": "Vhw3"},
	{"source": "Vwz0", "target": "Onn9"},
	{"source": "Nsq9", "target": "V_x7"},
	{"source": "W_x4", "target": "Pbv8"},
	{"source": "W_x4", "target": "Rpq8"},
	{"source": "Xwl1", "target": "Qw_3"},
	{"source": "Myw1", "target": "Xal9"},
	{"source": "Myw1", "target": "Rkq2"},
	{"source": "Pje9", "target": "Okb2"},
	{"source": "Zr_5", "target": "Rpq8"},
	{"source": "Zr_5", "target": "Myk3"},
	{"source": "B_g8", "target": "Gmg2"},
	{"source": "B_g8", "target": "Uzt1"},
	{"source": "B_g8", "target": "Bqp8"},
	{"source": "B_g8", "target": "Izv3"},
	{"source": "Hxi7", "target": "Qjw3"},
	{"source": "Hxi7", "target": "Qjb5"},
	{"source": "Icw5", "target": "Rfg7"},
	{"source": "Icw5", "target": "Urd4"},
	{"source": "Blu3", "target": "Cbt0"},
	{"source": "Blu3", "target": "Bak4"},
	{"source": "Tvx6", "target": "Zyf8"},
	{"source": "Tvx6", "target": "Imk5"},
	{"source": "Cqm4", "target": "Khl3"},
	{"source": "Cqm4", "target": "Uxk0"},
	{"source": "Gsa4", "target": "Kxq0"},
	{"source": "Gsa4", "target": "Ngn7"},
	{"source": "Ibg4", "target": "Jez4"},
	{"source": "Ibg4", "target": "Qxa8"},
	{"source": "D_j1", "target": "Pvi0"},
	{"source": "D_j1", "target": "Grl5"},
	{"source": "Nrr0", "target": "Cxy0"},
	{"source": "Nrr0", "target": "Im_4"},
	{"source": "J_q8", "target": "Trf9"},
	{"source": "J_q8", "target": "V_b6"},
	{"source": "Ged9", "target": "T_l2"},
	{"source": "Ged9", "target": "T_o9"},
	{"source": "D_j9", "target": "Fzs7"},
	{"source": "D_j9", "target": "A_g6"},
	{"source": "Ggd0", "target": "Pie5"},
	{"source": "Ggd0", "target": "Exl0"},
	{"source": "Vsk8", "target": "Eup7"},
	{"source": "Vsk8", "target": "Qyw1"},
	{"source": "Aml0", "target": "Aou3"},
	{"source": "Aml0", "target": "Vy_2"},
	{"source": "Neu3", "target": "Wmn5"},
	{"source": "Neu3", "target": "Mfa0"},
	{"source": "Kaj7", "target": "Bgx2"},
	{"source": "Kaj7", "target": "Kep0"},
	{"source": "Dlx5", "target": "Xhw2"},
	{"source": "Dlx5", "target": "Elo0"},
	{"source": "X_r4", "target": "Omx3"},
	{"source": "Kkh8", "target": "X__7"},
	{"source": "Kkh8", "target": "Ies9"},
	{"source": "Kkh8", "target": "Kkc9"},
	{"source": "Twh9", "target": "Wkq7"},
	{"source": "Twh9", "target": "Tj_9"},
	{"source": "Yky0", "target": "Q_t6"},
	{"source": "Ppe0", "target": "Dgw1"},
	{"source": "Aim7", "target": "Fs_5"},
	{"source": "Aim7", "target": "Mbu7"},
	{"source": "Kdz9", "target": "Ald5"},
	{"source": "Kdz9", "target": "Cbt0"},
	{"source": "Ela0", "target": "N_n9"},
	{"source": "Ela0", "target": "Kft9"},
	{"source": "Fwh9", "target": "Jqy9"},
	{"source": "Fwh9", "target": "Zkz1"},
	{"source": "Fik8", "target": "F_s4"},
	{"source": "Fik8", "target": "Bmz5"},
	{"source": "Mkk2", "target": "Bci0"},
	{"source": "Mkk2", "target": "Quz9"},
	{"source": "Pmf1", "target": "N_t9"},
	{"source": "Pmf1", "target": "Krx1"},
	{"source": "Hbo7", "target": "Kft9"},
	{"source": "Hbo7", "target": "Zpo1"},
	{"source": "Kdj7", "target": "Glk9"},
	{"source": "Spq8", "target": "Onn9"},
	{"source": "Spq8", "target": "Geg5"},
	{"source": "Z_u2", "target": "Ida1"},
	{"source": "Z_u2", "target": "Div8"},
	{"source": "Glt5", "target": "Bsq1"},
	{"source": "Glt5", "target": "J_s4"},
	{"source": "Ggu8", "target": "Wwr9"},
	{"source": "Ggu8", "target": "Mfg7"},
	{"source": "Ob_6", "target": "Rwl1"},
	{"source": "Ob_6", "target": "G_q7"},
	{"source": "Vnm8", "target": "Shd2"},
	{"source": "Oc_2", "target": "Dgw5"},
	{"source": "Oc_2", "target": "Obh6"},
	{"source": "Zjs0", "target": "Tdw2"},
	{"source": "Zjs0", "target": "Rea6"},
	{"source": "Zjs0", "target": "Bqp8"},
	{"source": "Nss6", "target": "Tvb2"},
	{"source": "Nss6", "target": "Awc6"},
	{"source": "Eup7", "target": "Avs7"},
	{"source": "Eup7", "target": "Vsk8"},
	{"source": "Krx1", "target": "Vy_2"},
	{"source": "Krx1", "target": "Pmf1"},
	{"source": "Zdd0", "target": "Tyr3"},
	{"source": "Zdd0", "target": "Se_5"},
	{"source": "Cm_6", "target": "Bwf5"},
	{"source": "Cm_6", "target": "Mfi7"},
	{"source": "Bxt9", "target": "Nrz8"},
	{"source": "Yjz7", "target": "Mdh5"},
	{"source": "Yjz7", "target": "Jqy9"},
	{"source": "Q_s0", "target": "Kvn9"},
	{"source": "Nku2", "target": "X__7"},
	{"source": "Ac_0", "target": "Yw_5"},
	{"source": "Ac_0", "target": "Rcf2"},
	{"source": "Zdd4", "target": "Yrs7"},
	{"source": "Zdd4", "target": "K_o7"},
	{"source": "Dak7", "target": "Aou3"},
	{"source": "Dak7", "target": "At_4"},
	{"source": "Zpr0", "target": "Cqf4"},
	{"source": "Zpr0", "target": "Oih9"},
	{"source": "Y_l8", "target": "Xvr2"},
	{"source": "Y_l8", "target": "Jis8"},
	{"source": "Y_l8", "target": "Att4"},
	{"source": "Y_l8", "target": "Gei8"},
	{"source": "Rdk2", "target": "Vtp6"},
	{"source": "Rdk2", "target": "Msk1"},
	{"source": "Rdk2", "target": "Uxk0"},
	{"source": "Gvb9", "target": "Bqj5"},
	{"source": "Gvb9", "target": "T_l2"},
	{"source": "Wzd6", "target": "Opd1"},
	{"source": "Wzd6", "target": "Xog0"},
	{"source": "Bgx2", "target": "Kaj7"},
	{"source": "Bgx2", "target": "Kvn9"},
	{"source": "Ryw2", "target": "Jkd5"},
	{"source": "V_q1", "target": "Ttf9"},
	{"source": "V_q1", "target": "Cgb8"},
	{"source": "J_s4", "target": "Spm8"},
	{"source": "J_s4", "target": "Glt5"},
	{"source": "Ibi4", "target": "Kep0"},
	{"source": "Ibi4", "target": "Uzt1"},
	{"source": "Suq5", "target": "Tj_9"},
	{"source": "Sob4", "target": "Fhi4"},
	{"source": "Sob4", "target": "B_c0"},
	{"source": "Gmu1", "target": "Gg_6"},
	{"source": "Gmu1", "target": "Aza1"},
	{"source": "Bci0", "target": "Mkk2"},
	{"source": "Bci0", "target": "Nvh8"},
	{"source": "Bci0", "target": "Wfp4"},
	{"source": "Bci0", "target": "Xhi7"},
	{"source": "I_j1", "target": "Eod3"},
	{"source": "I_j1", "target": "Gy_1"},
	{"source": "Wkx9", "target": "Jsu2"},
	{"source": "Wkx9", "target": "Tka0"},
	{"source": "Rfk5", "target": "Cen5"},
	{"source": "Rfk5", "target": "Nas7"},
	{"source": "Kux7", "target": "Cfw2"},
	{"source": "Kux7", "target": "Ksb1"},
	{"source": "Xgr8", "target": "Woi3"},
	{"source": "Xgr8", "target": "Tnw2"},
	{"source": "Urd4", "target": "Icw5"},
	{"source": "Urd4", "target": "Bro5"},
	{"source": "Doi2", "target": "Dhp5"},
	{"source": "Doi2", "target": "Csd4"},
	{"source": "Onn9", "target": "Spq8"},
	{"source": "Onn9", "target": "Vwz0"},
	{"source": "Vtm7", "target": "Plk6"},
	{"source": "Vtm7", "target": "Gei8"},
	{"source": "T_o9", "target": "Ged9"},
	{"source": "T_o9", "target": "Te_1"},
	{"source": "Pxe6", "target": "Hpb4"},
	{"source": "Pxe6", "target": "Xks1"},
	{"source": "Ydl0", "target": "Suh9"},
	{"source": "Ydl0", "target": "Xal9"},
	{"source": "Ydl0", "target": "Sty9"},
	{"source": "Ydl0", "target": "Aqb8"},
	{"source": "Bkx1", "target": "Qt_8"},
	{"source": "Bkx1", "target": "Slf2"},
	{"source": "Bkx1", "target": "Ujr8"},
	{"source": "Ubx4", "target": "Te_1"},
	{"source": "Ubx4", "target": "Rec8"},
	{"source": "Bjx9", "target": "Pcn6"},
	{"source": "Bjx9", "target": "Rw_2"},
	{"source": "Shd2", "target": "Tre6"},
	{"source": "Shd2", "target": "Aih7"},
	{"source": "Shd2", "target": "Zmc7"},
	{"source": "Shd2", "target": "Vnm8"},
	{"source": "Zmc7", "target": "Swh3"},
	{"source": "Zmc7", "target": "Shd2"},
	{"source": "Ofp4", "target": "Opt4"},
	{"source": "Ofp4", "target": "Xhc2"},
	{"source": "Mml9", "target": "Brq7"},
	{"source": "Mml9", "target": "Rec8"},
	{"source": "Msk1", "target": "Rdk2"},
	{"source": "Msk1", "target": "Vpy1"},
	{"source": "Msk1", "target": "Zvn0"},
	{"source": "Oaq8", "target": "F_t5"},
	{"source": "Oaq8", "target": "Wmn5"},
	{"source": "Ah_0", "target": "Agk3"},
	{"source": "Ah_0", "target": "Aee8"},
	{"source": "Qt_8", "target": "Bkx1"},
	{"source": "Uoe5", "target": "Tnw2"},
	{"source": "Uoe5", "target": "Vlb4"},
	{"source": "Ynj6", "target": "Vrs5"},
	{"source": "Ynj6", "target": "Eci4"},
	{"source": "Q_t6", "target": "Bqj5"},
	{"source": "Q_t6", "target": "Yky0"},
	{"source": "H_a7", "target": "J_v7"},
	{"source": "Zjd3", "target": "Bjd7"},
	{"source": "Zjd3", "target": "Bqo7"},
	{"source": "Xhb4", "target": "K_n0"},
	{"source": "Ruy0", "target": "Tka0"},
	{"source": "Ruy0", "target": "Zqs7"},
	{"source": "Ivv7", "target": "Wrk8"},
	{"source": "Ivv7", "target": "Pkk2"},
	{"source": "Fen4", "target": "Z_i7"},
	{"source": "Fen4", "target": "Ter1"},
	{"source": "Geg5", "target": "Spq8"},
	{"source": "Geg5", "target": "Yw_5"},
	{"source": "Unv1", "target": "Snm1"},
	{"source": "Unv1", "target": "Brq7"},
	{"source": "Zqs7", "target": "Mtv0"},
	{"source": "Zqs7", "target": "Ruy0"},
	{"source": "Esr9", "target": "Xhw2"},
	{"source": "Esr9", "target": "Hnp4"},
	{"source": "Qw_3", "target": "Tfw4"},
	{"source": "Qw_3", "target": "Quc9"},
	{"source": "Qw_3", "target": "Xwl1"},
	{"source": "Cgb8", "target": "V_q1"},
	{"source": "Cgb8", "target": "Pwg7"},
	{"source": "Wyf1", "target": "J_u4"},
	{"source": "Wyf1", "target": "Qyz1"},
	{"source": "V_b6", "target": "Rpf0"},
	{"source": "V_b6", "target": "J_q8"},
	{"source": "Qpq7", "target": "Nrz8"},
	{"source": "Qpq7", "target": "Qei5"},
	{"source": "Jdc6", "target": "Px_8"},
	{"source": "Jdc6", "target": "Nuv0"},
	{"source": "Jdc6", "target": "B_v6"},
	{"source": "Pky9", "target": "Qjh9"},
	{"source": "Pky9", "target": "Att4"},
	{"source": "Pky9", "target": "Pxm2"},
	{"source": "Njw4", "target": "Cxj5"},
	{"source": "Qjb5", "target": "Hxi7"},
	{"source": "Qjb5", "target": "Ulp3"},
	{"source": "Bii2", "target": "Dev3"},
	{"source": "Bii2", "target": "Iwk0"},
	{"source": "Uzt1", "target": "B_g8"},
	{"source": "Uzt1", "target": "Ibi4"},
	{"source": "Gvd4", "target": "Kft9"},
	{"source": "Izv3", "target": "B_g8"},
	{"source": "Bwf5", "target": "F_t5"},
	{"source": "Bwf5", "target": "Cm_6"},
	{"source": "Oym3", "target": "B_s6"},
	{"source": "Oym3", "target": "Hzu3"},
	{"source": "Cbt0", "target": "Kdz9"},
	{"source": "Cbt0", "target": "Blu3"},
	{"source": "Qfc4", "target": "Mf_8"},
	{"source": "Qfc4", "target": "Hth4"},
	{"source": "Teo8", "target": "Amj8"},
	{"source": "Teo8", "target": "Bko7"},
	{"source": "Teo9", "target": "Dmc7"},
	{"source": "Teo9", "target": "Bqp8"},
	{"source": "Vgq8", "target": "Hgt4"},
	{"source": "Vgq8", "target": "Bxr6"},
	{"source": "K_n0", "target": "Xhb4"},
	{"source": "K_n0", "target": "Vig8"},
	{"source": "K_n0", "target": "Auc2"},
	{"source": "Khl3", "target": "Cqm4"},
	{"source": "Khl3", "target": "Thw9"},
	{"source": "Xhc2", "target": "Hgr7"},
	{"source": "Xhc2", "target": "Ofp4"},
	{"source": "Sku2", "target": "Eod3"},
	{"source": "Sku2", "target": "Plk6"},
	{"source": "Irx2", "target": "Thw9"},
	{"source": "Jy_6", "target": "Egv2"},
	{"source": "Jy_6", "target": "N_l5"},
	{"source": "Zod2", "target": "Uxk0"},
	{"source": "Bak4", "target": "Blu3"},
	{"source": "Bak4", "target": "Glk9"},
	{"source": "J_u4", "target": "Pkb1"},
	{"source": "J_u4", "target": "Wyf1"},
	{"source": "Te_1", "target": "J_v7"},
	{"source": "Te_1", "target": "Ubx4"},
	{"source": "Te_1", "target": "T_o9"},
	{"source": "Ssc3", "target": "N_n9"},
	{"source": "Ssc3", "target": "Spm8"},
	{"source": "Xks1", "target": "Pxe6"},
	{"source": "Xks1", "target": "Aza1"},
	{"source": "Wij2", "target": "Q_f8"},
	{"source": "Wij2", "target": "Ppb7"},
	{"source": "Myk3", "target": "Zr_5"},
	{"source": "Myk3", "target": "F_t6"},
	{"source": "Myk3", "target": "Dwt9"},
	{"source": "Md_6", "target": "Fzs7"},
	{"source": "Md_6", "target": "Nyi4"},
	{"source": "Qdd1", "target": "Cfw2"},
	{"source": "Qdd1", "target": "Mmc3"},
	{"source": "Qsq8", "target": "Hbj8"},
	{"source": "Qsq8", "target": "Qei5"},
	{"source": "Sff1", "target": "N_t9"},
	{"source": "Sff1", "target": "Hz_1"},
	{"source": "Gyd1", "target": "Nx_6"},
	{"source": "Gyd1", "target": "Ujk6"},
	{"source": "Jhc2", "target": "Mtv0"},
	{"source": "Jhc2", "target": "Jim3"},
	{"source": "Yzi0", "target": "Gt_2"},
	{"source": "Yzi0", "target": "Zdh5"},
	{"source": "Jis8", "target": "Y_l8"},
	{"source": "Hp_1", "target": "O_n5"},
	{"source": "Uix9", "target": "Fqr0"},
	{"source": "Uix9", "target": "Wb_6"},
	{"source": "Ivg6", "target": "Kvn9"},
	{"source": "Hmp4", "target": "Rwl1"},
	{"source": "Hmp4", "target": "Nvh8"},
	{"source": "Hmp4", "target": "Rqk3"},
	{"source": "Vr_1", "target": "Bh_7"},
	{"source": "Vr_1", "target": "Aei7"},
	{"source": "Woi3", "target": "Xgr8"},
	{"source": "Woi3", "target": "Cnf1"},
	{"source": "Woi3", "target": "S_m5"},
	{"source": "Pwg7", "target": "Cgb8"},
	{"source": "Pwg7", "target": "Bzo4"},
	{"source": "Pwg7", "target": "Imb1"},
	{"source": "Egv2", "target": "Fn_4"},
	{"source": "Egv2", "target": "Jy_6"},
	{"source": "I_l5", "target": "Kzk7"},
	{"source": "I_l5", "target": "A_d1"},
	{"source": "Ney2", "target": "Jlf0"},
	{"source": "Ney2", "target": "Emy6"},
	{"source": "Eod3", "target": "I_j1"},
	{"source": "Eod3", "target": "Sku2"},
	{"source": "Hnp4", "target": "Wkq7"},
	{"source": "Hnp4", "target": "Esr9"},
	{"source": "Mf_8", "target": "Qfc4"},
	{"source": "Mf_8", "target": "Ndq1"},
	{"source": "Rqk3", "target": "Hmp4"},
	{"source": "Gmg2", "target": "B_g8"},
	{"source": "C_e9", "target": "Das7"},
	{"source": "C_e9", "target": "Vrs5"},
	{"source": "N_j8", "target": "Ida1"},
	{"source": "N_j8", "target": "Gyo4"},
	{"source": "G_j3", "target": "Rrr1"},
	{"source": "Nuv0", "target": "Wmo3"},
	{"source": "Nuv0", "target": "Jdc6"},
	{"source": "Xce5", "target": "Uyf7"},
	{"source": "Xce5", "target": "Ddp4"},
	{"source": "K_o7", "target": "Xjg8"},
	{"source": "K_o7", "target": "Zdd4"},
	{"source": "J_v7", "target": "H_a7"},
	{"source": "J_v7", "target": "Te_1"},
	{"source": "Jit5", "target": "Xqw5"},
	{"source": "Jit5", "target": "Gzx5"},
	{"source": "Qfu0", "target": "Snm1"},
	{"source": "Bmz5", "target": "Rfg7"},
	{"source": "Bmz5", "target": "Fik8"},
	{"source": "Hgr7", "target": "Xhc2"},
	{"source": "Hgr7", "target": "Quz9"},
	{"source": "Gei8", "target": "Y_l8"},
	{"source": "Gei8", "target": "Vtm7"},
	{"source": "P_m4", "target": "Xqw5"},
	{"source": "P_m4", "target": "Fze5"},
	{"source": "Tj_9", "target": "Hax2"},
	{"source": "Tj_9", "target": "Twh9"},
	{"source": "Tj_9", "target": "Suq5"},
	{"source": "Q_f8", "target": "U_b7"},
	{"source": "Q_f8", "target": "Wij2"},
	{"source": "At_4", "target": "Vtu8"},
	{"source": "At_4", "target": "Blm8"},
	{"source": "At_4", "target": "Dak7"},
	{"source": "Xvr2", "target": "Y_l8"},
	{"source": "D__0", "target": "Ugz8"},
	{"source": "D__0", "target": "Yma1"},
	{"source": "Jyq2", "target": "Ies9"},
	{"source": "Jyq2", "target": "Ppb7"},
	{"source": "Slf2", "target": "Bkx1"},
	{"source": "Slf2", "target": "Wlp1"},
	{"source": "Slf2", "target": "Cd_2"},
	{"source": "Slf2", "target": "C_z0"},
	{"source": "Vtp6", "target": "Mhr1"},
	{"source": "Vtp6", "target": "Rdk2"},
	{"source": "Vib6", "target": "Qtl4"},
	{"source": "Vib6", "target": "Vej9"},
	{"source": "Qxa8", "target": "Jlf0"},
	{"source": "Qxa8", "target": "Ibg4"},
	{"source": "Pkk2", "target": "Ivv7"},
	{"source": "Pkk2", "target": "Qjh9"},
	{"source": "Z_i7", "target": "Fen4"},
	{"source": "Z_i7", "target": "Rby8"},
	{"source": "Wlk2", "target": "Av_1"},
	{"source": "Wlk2", "target": "Isn1"},
	{"source": "Zdh5", "target": "Zyf8"},
	{"source": "Zdh5", "target": "Yzi0"},
	{"source": "Aes1", "target": "Iwk0"},
	{"source": "Aes1", "target": "Fs_5"},
	{"source": "Av_1", "target": "Wlk2"},
	{"source": "Av_1", "target": "Gco2"},
	{"source": "Ugz8", "target": "Hax2"},
	{"source": "Ugz8", "target": "D__0"},
	{"source": "A_d1", "target": "I_l5"},
	{"source": "A_d1", "target": "W_d9"},
	{"source": "Vy_2", "target": "Krx1"},
	{"source": "Vy_2", "target": "Aml0"},
	{"source": "Pvi0", "target": "Eoh8"},
	{"source": "Pvi0", "target": "D_j1"},
	{"source": "Jkd5", "target": "Ryw2"},
	{"source": "Jkd5", "target": "O_n5"},
	{"source": "Jkd5", "target": "Rkq2"},
	{"source": "Hx_1", "target": "Mfi7"},
	{"source": "Hx_1", "target": "Pwb5"},
	{"source": "Plk6", "target": "Gwp7"},
	{"source": "Plk6", "target": "Vtm7"},
	{"source": "Plk6", "target": "Sku2"},
	{"source": "Uyf7", "target": "Jd_0"},
	{"source": "Uyf7", "target": "Xce5"},
	{"source": "Uyf7", "target": "Oau8"},
	{"source": "Xju7", "target": "Div8"},
	{"source": "Xju7", "target": "Dur5"},
	{"source": "Qss4", "target": "Swh3"},
	{"source": "Qss4", "target": "H_h8"},
	{"source": "Mm_8", "target": "Joe7"},
	{"source": "Okb2", "target": "N_q9"},
	{"source": "Okb2", "target": "Kzk7"},
	{"source": "Okb2", "target": "Pje9"},
	{"source": "Da_7", "target": "Oz_3"},
	{"source": "Da_7", "target": "S_k1"},
	{"source": "Nyf5", "target": "Csd4"},
	{"source": "Nyf5", "target": "Hzu3"},
	{"source": "F_b3", "target": "Nkk3"},
	{"source": "F_b3", "target": "Zuy9"},
	{"source": "Mn_4", "target": "B_c0"},
	{"source": "Mn_4", "target": "P_q7"},
	{"source": "Vlb4", "target": "Uoe5"},
	{"source": "Vlb4", "target": "S_k1"},
	{"source": "Oz_3", "target": "Cyz9"},
	{"source": "Oz_3", "target": "Da_7"},
	{"source": "Vjs2", "target": "Xnu9"},
	{"source": "Vjs2", "target": "Mbu4"},
	{"source": "Xef4", "target": "F_t6"},
	{"source": "Xef4", "target": "Ksb1"},
	{"source": "Pnk3", "target": "Qhn1"},
	{"source": "Pnk3", "target": "Itn8"},
	{"source": "Fn_4", "target": "Gg_6"},
	{"source": "Fn_4", "target": "Egv2"},
	{"source": "Mfa0", "target": "Ter1"},
	{"source": "Mfa0", "target": "Neu3"},
	{"source": "Imk5", "target": "Tvx6"},
	{"source": "Imk5", "target": "Ald5"},
	{"source": "Bqj5", "target": "Q_t6"},
	{"source": "Bqj5", "target": "Gvb9"},
	{"source": "Bqj5", "target": "Amj8"},
	{"source": "Hz_1", "target": "Mtt0"},
	{"source": "Hz_1", "target": "Sff1"},
	{"source": "Xod9", "target": "Tfe8"},
	{"source": "Xod9", "target": "Aih7"},
	{"source": "Ter1", "target": "Mfa0"},
	{"source": "Ter1", "target": "Fen4"},
	{"source": "N_l5", "target": "Jy_6"},
	{"source": "N_l5", "target": "Itb6"},
	{"source": "Fo_7", "target": "Jtj9"},
	{"source": "Fo_7", "target": "Ddp4"},
	{"source": "Oau8", "target": "Uyf7"},
	{"source": "F_s4", "target": "Sak2"},
	{"source": "F_s4", "target": "Fik8"},
	{"source": "Kzk7", "target": "I_l5"},
	{"source": "Kzk7", "target": "Okb2"},
	{"source": "Rwl1", "target": "Ob_6"},
	{"source": "Rwl1", "target": "Hmp4"},
	{"source": "Xnu9", "target": "Qjw3"},
	{"source": "Xnu9", "target": "Vjs2"},
	{"source": "Eci4", "target": "Ynj6"},
	{"source": "Eci4", "target": "Dhp5"},
	{"source": "Quc9", "target": "Qw_3"},
	{"source": "Quc9", "target": "W_d9"},
	{"source": "Zog4", "target": "Jij2"},
	{"source": "Zog4", "target": "Wyr3"},
	{"source": "Hgt4", "target": "Vgq8"},
	{"source": "Hgt4", "target": "Pxq8"},
	{"source": "Pcn6", "target": "Bjx9"},
	{"source": "Pcn6", "target": "Mfg7"},
	{"source": "Kep0", "target": "Kaj7"},
	{"source": "Kep0", "target": "Ibi4"},
	{"source": "Wrk8", "target": "Ivv7"},
	{"source": "Wrk8", "target": "Qrv0"},
	{"source": "Wjm0", "target": "P_q7"},
	{"source": "Wjm0", "target": "Hpb4"},
	{"source": "Tka0", "target": "Wkx9"},
	{"source": "Tka0", "target": "Ruy0"},
	{"source": "Ddp4", "target": "Fo_7"},
	{"source": "Ddp4", "target": "Xce5"},
	{"source": "Gjj9", "target": "Yby1"},
	{"source": "Gjj9", "target": "Mtt0"},
	{"source": "Yi_9", "target": "Jij2"},
	{"source": "Yi_9", "target": "Ujk6"},
	{"source": "Hpb4", "target": "Pxe6"},
	{"source": "Hpb4", "target": "Wjm0"},
	{"source": "Mhr1", "target": "Vtp6"},
	{"source": "Fs_5", "target": "Aes1"},
	{"source": "Fs_5", "target": "Aim7"},
	{"source": "H_v6", "target": "H_h8"},
	{"source": "H_v6", "target": "Zuy9"},
	{"source": "Xhw2", "target": "Dlx5"},
	{"source": "Xhw2", "target": "Esr9"},
	{"source": "Mds0", "target": "Rcq1"},
	{"source": "Rcq1", "target": "Mds0"},
	{"source": "Rcq1", "target": "B_s6"},
	{"source": "Cfw2", "target": "Kux7"},
	{"source": "Cfw2", "target": "Qdd1"},
	{"source": "Nvh8", "target": "Hmp4"},
	{"source": "Nvh8", "target": "Bci0"},
	{"source": "Xmv7", "target": "Bzo4"},
	{"source": "Xmv7", "target": "Yma1"},
	{"source": "S_k1", "target": "Da_7"},
	{"source": "S_k1", "target": "Vlb4"},
	{"source": "Vee6", "target": "Fzu6"},
	{"source": "Vee6", "target": "Cen5"},
	{"source": "Csd4", "target": "Doi2"},
	{"source": "Csd4", "target": "Nyf5"},
	{"source": "F_t5", "target": "Bwf5"},
	{"source": "F_t5", "target": "Oaq8"},
	{"source": "Ujk6", "target": "Yi_9"},
	{"source": "Ujk6", "target": "Gyd1"},
	{"source": "F_t6", "target": "Myk3"},
	{"source": "F_t6", "target": "Xef4"},
	{"source": "Joe7", "target": "Sty9"},
	{"source": "Joe7", "target": "Wk_4"},
	{"source": "Joe7", "target": "Mm_8"},
	{"source": "Noj1", "target": "Gy_1"},
	{"source": "Noj1", "target": "Qyw1"},
	{"source": "Aqb8", "target": "Ydl0"},
	{"source": "Jlf0", "target": "Ney2"},
	{"source": "Jlf0", "target": "Qxa8"},
	{"source": "Jfg9", "target": "Avc6"},
	{"source": "Jfg9", "target": "Opt4"},
	{"source": "Vrs5", "target": "C_e9"},
	{"source": "Vrs5", "target": "Ynj6"},
	{"source": "Wb_6", "target": "C__7"},
	{"source": "Wb_6", "target": "Uix9"},
	{"source": "Qjw3", "target": "Xnu9"},
	{"source": "Qjw3", "target": "Hxi7"},
	{"source": "Dhp5", "target": "Eci4"},
	{"source": "Dhp5", "target": "Doi2"},
	{"source": "Nkk3", "target": "Zjz0"},
	{"source": "Nkk3", "target": "F_b3"},
	{"source": "Gzx5", "target": "Qlw5"},
	{"source": "Gzx5", "target": "Jit5"},
	{"source": "Ilm5", "target": "Omx3"},
	{"source": "Ilm5", "target": "Vig8"},
	{"source": "Jsu2", "target": "Wkx9"},
	{"source": "Jsu2", "target": "Wlp1"},
	{"source": "Jsu2", "target": "Zco2"},
	{"source": "Ucm1", "target": "U_b7"},
	{"source": "Ucm1", "target": "Rgg3"},
	{"source": "Sak2", "target": "Hju3"},
	{"source": "Sak2", "target": "F_s4"},
	{"source": "Sak2", "target": "Jd_0"},
	{"source": "Zyf8", "target": "Zdh5"},
	{"source": "Zyf8", "target": "Tvx6"},
	{"source": "Vju2", "target": "Eoh8"},
	{"source": "Iwk0", "target": "Aes1"},
	{"source": "Iwk0", "target": "Bii2"},
	{"source": "Nrz8", "target": "Hsu7"},
	{"source": "Nrz8", "target": "Qpq7"},
	{"source": "Nrz8", "target": "Bxt9"},
	{"source": "Hqs9", "target": "Xky1"},
	{"source": "Hqs9", "target": "Uip0"},
	{"source": "Aee8", "target": "Vhw3"},
	{"source": "Aee8", "target": "Ah_0"},
	{"source": "Zjz0", "target": "Wk_4"},
	{"source": "Zjz0", "target": "Nkk3"},
	{"source": "Blm8", "target": "At_4"},
	{"source": "Blm8", "target": "Gxn3"},
	{"source": "Xjg8", "target": "K_o7"},
	{"source": "Xjg8", "target": "Dmc7"},
	{"source": "Rea6", "target": "Zjs0"},
	{"source": "Rea6", "target": "Vpy1"},
	{"source": "Qlw5", "target": "Gzx5"},
	{"source": "Qlw5", "target": "Mdh5"},
	{"source": "Aza1", "target": "Xks1"},
	{"source": "Aza1", "target": "Gmu1"},
	{"source": "Cnf1", "target": "Woi3"},
	{"source": "Cnf1", "target": "Oih9"},
	{"source": "Hju3", "target": "Sak2"},
	{"source": "Glk9", "target": "Kdj7"},
	{"source": "Glk9", "target": "Ndq1"},
	{"source": "Glk9", "target": "Bak4"},
	{"source": "Zkz1", "target": "Fwh9"},
	{"source": "Zkz1", "target": "Vvy2"},
	{"source": "Eoh8", "target": "Pvi0"},
	{"source": "Eoh8", "target": "Sdl6"},
	{"source": "Eoh8", "target": "Vju2"},
	{"source": "Qrv0", "target": "Wrk8"},
	{"source": "Qrv0", "target": "Dev3"},
	{"source": "N_n9", "target": "Ssc3"},
	{"source": "N_n9", "target": "Ela0"},
	{"source": "Ald5", "target": "Imk5"},
	{"source": "Ald5", "target": "Kdz9"},
	{"source": "Qfh7", "target": "Fzu6"},
	{"source": "Emy6", "target": "Ney2"},
	{"source": "Opt4", "target": "Jfg9"},
	{"source": "Opt4", "target": "Ofp4"},
	{"source": "Pd_9", "target": "Xpk8"},
	{"source": "Pd_9", "target": "Zry0"},
	{"source": "Pd_9", "target": "Vvt7"},
	{"source": "Wmn5", "target": "Neu3"},
	{"source": "Wmn5", "target": "Oaq8"},
	{"source": "Kvn9", "target": "Bgx2"},
	{"source": "Kvn9", "target": "Wyr3"},
	{"source": "Kvn9", "target": "Ivg6"},
	{"source": "Kvn9", "target": "Q_s0"},
	{"source": "A_g6", "target": "Grl5"},
	{"source": "A_g6", "target": "D_j9"},
	{"source": "A_g6", "target": "Ouv4"},
	{"source": "C_z0", "target": "Slf2"},
	{"source": "Jpf7", "target": "Ovv4"},
	{"source": "Jpf7", "target": "Das7"},
	{"source": "V_x7", "target": "Nsq9"},
	{"source": "V_x7", "target": "Qtl4"},
	{"source": "V_x7", "target": "Hbl2"},
	{"source": "Opd1", "target": "Uhm2"},
	{"source": "Opd1", "target": "Wzd6"},
	{"source": "Nyi4", "target": "Md_6"},
	{"source": "Nyi4", "target": "Qjy7"},
	{"source": "Jix5", "target": "Orz5"},
	{"source": "Jix5", "target": "Gyo4"},
	{"source": "Zry0", "target": "Ndp0"},
	{"source": "Zry0", "target": "Pd_9"},
	{"source": "Mbu4", "target": "Vjs2"},
	{"source": "Mbu4", "target": "D_v0"},
	{"source": "Uhm2", "target": "Fhi4"},
	{"source": "Uhm2", "target": "Opd1"},
	{"source": "Rkq2", "target": "Myw1"},
	{"source": "Rkq2", "target": "Jkd5"},
	{"source": "Rkq2", "target": "Mss3"},
	{"source": "Xog0", "target": "Bqp8"},
	{"source": "Xog0", "target": "Wzd6"},
	{"source": "P_q7", "target": "Wjm0"},
	{"source": "P_q7", "target": "Mn_4"},
	{"source": "Mbu7", "target": "Hbl2"},
	{"source": "Mbu7", "target": "Aim7"},
	{"source": "Cqf4", "target": "Zpr0"},
	{"source": "Cqf4", "target": "Yrq3"},
	{"source": "Fqr0", "target": "Uix9"},
	{"source": "Fqr0", "target": "Sdp4"},
	{"source": "Jfy4", "target": "Ugn1"},
	{"source": "Jfy4", "target": "Px_8"},
	{"source": "Xqw5", "target": "P_m4"},
	{"source": "Xqw5", "target": "Jit5"},
	{"source": "Qei5", "target": "Qpq7"},
	{"source": "Qei5", "target": "Qsq8"},
	{"source": "Wfp4", "target": "Bci0"},
	{"source": "Avs7", "target": "Dle9"},
	{"source": "Avs7", "target": "Eup7"},
	{"source": "Avs7", "target": "Idf8"},
	{"source": "Vpu2", "target": "Ugn1"},
	{"source": "Vpu2", "target": "Pxq8"},
	{"source": "Auc2", "target": "K_n0"},
	{"source": "Auc2", "target": "Bqo7"},
	{"source": "Zsy7", "target": "Mmc3"},
	{"source": "Zsy7", "target": "Bsq1"},
	{"source": "Nrk3", "target": "Ouw5"},
	{"source": "Nrk3", "target": "Vvt7"},
	{"source": "Suh9", "target": "Ydl0"},
	{"source": "Das7", "target": "C_e9"},
	{"source": "Das7", "target": "Jpf7"},
	{"source": "Qjh9", "target": "Pkk2"},
	{"source": "Qjh9", "target": "Pky9"},
	{"source": "Hax2", "target": "Tj_9"},
	{"source": "Hax2", "target": "Ugz8"},
	{"source": "Bxl1", "target": "Wyr3"},
	{"source": "Cpw4", "target": "Zpo1"},
	{"source": "Cpw4", "target": "Rgg3"},
	{"source": "S_m5", "target": "Woi3"},
	{"source": "Avc4", "target": "C__7"},
	{"source": "Ajv2", "target": "Nx_6"},
	{"source": "Swh3", "target": "Qss4"},
	{"source": "Swh3", "target": "Zmc7"},
	{"source": "Yma1", "target": "Xmv7"},
	{"source": "Yma1", "target": "D__0"},
	{"source": "Avc6", "target": "Jfg9"},
	{"source": "Avc6", "target": "Pbv8"},
	{"source": "H_h8", "target": "Qss4"},
	{"source": "H_h8", "target": "H_v6"},
	{"source": "Vhw3", "target": "Aee8"},
	{"source": "Vhw3", "target": "Vwz0"},
	{"source": "Deb7", "target": "Obh6"},
	{"source": "Mmc3", "target": "Zsy7"},
	{"source": "Mmc3", "target": "Qdd1"},
	{"source": "Sdl6", "target": "Eoh8"},
	{"source": "Sdl6", "target": "Aqh5"},
	{"source": "Aou3", "target": "Aeg0"},
	{"source": "Aou3", "target": "Dak7"},
	{"source": "Aou3", "target": "Aml0"},
	{"source": "Wmo3", "target": "Cyz9"},
	{"source": "Wmo3", "target": "Nuv0"},
	{"source": "Bh_7", "target": "D_v0"},
	{"source": "Bh_7", "target": "Vr_1"},
	{"source": "Bh_7", "target": "T_k3"},
	{"source": "Wk_4", "target": "Joe7"},
	{"source": "Wk_4", "target": "Zjz0"},
	{"source": "Vvt7", "target": "Nrk3"},
	{"source": "Vvt7", "target": "Pd_9"},
	{"source": "Att4", "target": "Y_l8"},
	{"source": "Att4", "target": "Pky9"},
	{"source": "Ugn1", "target": "Vpu2"},
	{"source": "Ugn1", "target": "Jfy4"},
	{"source": "Sty9", "target": "Joe7"},
	{"source": "Sty9", "target": "Ydl0"},
	{"source": "Sty9", "target": "Xuj4"},
	{"source": "Xhi7", "target": "Bci0"},
	{"source": "Zuy9", "target": "F_b3"},
	{"source": "Zuy9", "target": "H_v6"},
	{"source": "Xky1", "target": "Kpq8"},
	{"source": "Xky1", "target": "Hqs9"},
	{"source": "Aeg0", "target": "Aou3"},
	{"source": "Awc6", "target": "Obh6"},
	{"source": "Awc6", "target": "Nss6"},
	{"source": "Yw_5", "target": "Ac_0"},
	{"source": "Yw_5", "target": "Geg5"},
	{"source": "Gjm7", "target": "Vvy2"},
	{"source": "Gjm7", "target": "Okk4"},
	{"source": "Bko7", "target": "Cxy0"},
	{"source": "Bko7", "target": "Teo8"},
	{"source": "Rw_2", "target": "Jim3"},
	{"source": "Rw_2", "target": "Bjx9"},
	{"source": "Qjy7", "target": "Gx_4"},
	{"source": "Qjy7", "target": "Nyi4"},
	{"source": "Jez4", "target": "Ibg4"},
	{"source": "Jez4", "target": "Exl0"},
	{"source": "Obh6", "target": "Deb7"},
	{"source": "Obh6", "target": "Oc_2"},
	{"source": "Obh6", "target": "Awc6"},
	{"source": "Ngn7", "target": "Gsa4"},
	{"source": "Ngn7", "target": "Yrq3"},
	{"source": "Tfe8", "target": "Xod9"},
	{"source": "Tfe8", "target": "Ttf9"},
	{"source": "Pxm2", "target": "Pky9"},
	{"source": "Hzc5", "target": "Ndp0"},
	{"source": "Rpq8", "target": "W_x4"},
	{"source": "Rpq8", "target": "Zr_5"},
	{"source": "Isn1", "target": "Avf5"},
	{"source": "Isn1", "target": "Gx_4"},
	{"source": "Isn1", "target": "Wlk2"},
	{"source": "U_p9", "target": "Dgw1"},
	{"source": "U_p9", "target": "G_c7"},
	{"source": "Gco2", "target": "Av_1"},
	{"source": "Gco2", "target": "D_x9"},
	{"source": "Vtu8", "target": "At_4"},
	{"source": "Uxk0", "target": "Zod2"},
	{"source": "Uxk0", "target": "Rdk2"},
	{"source": "Uxk0", "target": "Cqm4"},
	{"source": "Rec8", "target": "Mml9"},
	{"source": "Rec8", "target": "Ubx4"},
	{"source": "Tvb2", "target": "Dur5"},
	{"source": "Tvb2", "target": "Nss6"},
	{"source": "Yrq3", "target": "Rrr3"},
	{"source": "Yrq3", "target": "Ngn7"},
	{"source": "Yrq3", "target": "Cqf4"},
	{"source": "Vig8", "target": "Ilm5"},
	{"source": "Vig8", "target": "K_n0"},
	{"source": "Wlp1", "target": "Jsu2"},
	{"source": "Wlp1", "target": "Slf2"},
	{"source": "Hsu7", "target": "Nrz8"},
	{"source": "Hsu7", "target": "Aqh5"},
	{"source": "Kpq8", "target": "Rpf0"},
	{"source": "Kpq8", "target": "Xky1"},
	{"source": "Im_4", "target": "Bqp8"},
	{"source": "Im_4", "target": "Nrr0"},
	{"source": "Ida1", "target": "Z_u2"},
	{"source": "Ida1", "target": "N_j8"},
	{"source": "Mss3", "target": "Rkq2"},
	{"source": "Mev3", "target": "Bqp8"},
	{"source": "Mev3", "target": "Zn_4"},
	{"source": "Grl5", "target": "D_j1"},
	{"source": "Grl5", "target": "A_g6"},
	{"source": "Tyr3", "target": "Zdd0"},
	{"source": "Tyr3", "target": "Zn_4"},
	{"source": "Itn8", "target": "Pnk3"},
	{"source": "Po_5", "target": "Pkb1"},
	{"source": "Po_5", "target": "Fnf8"},
	{"source": "Qyw1", "target": "Vsk8"},
	{"source": "Qyw1", "target": "Noj1"},
	{"source": "Tdw2", "target": "Zjs0"},
	{"source": "Aai6", "target": "Pwb5"},
	{"source": "Aai6", "target": "Pdb4"},
	{"source": "Jij2", "target": "Zog4"},
	{"source": "Jij2", "target": "Yi_9"},
	{"source": "Bqo7", "target": "Zjd3"},
	{"source": "Bqo7", "target": "Auc2"},
	{"source": "Ndp0", "target": "Zry0"},
	{"source": "Ndp0", "target": "Dgw5"},
	{"source": "Ndp0", "target": "Hzc5"},
	{"source": "Xal9", "target": "Ydl0"},
	{"source": "Xal9", "target": "Myw1"},
	{"source": "Kft9", "target": "Gvd4"},
	{"source": "Kft9", "target": "Hbo7"},
	{"source": "Kft9", "target": "Ela0"},
	{"source": "B_s6", "target": "Rcq1"},
	{"source": "B_s6", "target": "Oym3"},
	{"source": "B_s6", "target": "Bjd7"},
	{"source": "Bro5", "target": "Urd4"},
	{"source": "Bro5", "target": "G_q7"},
	{"source": "Wkq7", "target": "Hnp4"},
	{"source": "Wkq7", "target": "Twh9"},
	{"source": "Pdb4", "target": "Aai6"},
	{"source": "Pdb4", "target": "Nx_6"},
	{"source": "N_q9", "target": "Jti8"},
	{"source": "N_q9", "target": "Okb2"},
	{"source": "Rrr1", "target": "Rby8"},
	{"source": "Rrr1", "target": "G_j3"},
	{"source": "Jfk1", "target": "Hth4"},
	{"source": "Jfk1", "target": "Dfv1"},
	{"source": "Rrr3", "target": "Yrq3"},
	{"source": "B_c0", "target": "Mn_4"},
	{"source": "B_c0", "target": "Sob4"},
	{"source": "Oih9", "target": "Zpr0"},
	{"source": "Oih9", "target": "Cnf1"},
	{"source": "G_q7", "target": "Ob_6"},
	{"source": "G_q7", "target": "Bro5"},
	{"source": "Ouv4", "target": "A_g6"},
	{"source": "Tfw4", "target": "Qw_3"},
	{"source": "Dqr2", "target": "Hbj8"},
	{"source": "Mtt0", "target": "Gjj9"},
	{"source": "Mtt0", "target": "Hz_1"},
	{"source": "Gg_6", "target": "Fn_4"},
	{"source": "Gg_6", "target": "Gmu1"},
	{"source": "Jqy9", "target": "Yjz7"},
	{"source": "Jqy9", "target": "Fwh9"},
	{"source": "D_v0", "target": "Bh_7"},
	{"source": "D_v0", "target": "Mbu4"},
	{"source": "Kkc9", "target": "Kkh8"},
	{"source": "Ovv4", "target": "Jpf7"},
	{"source": "Ovv4", "target": "Ujr8"},
	{"source": "Hzu3", "target": "Nyf5"},
	{"source": "Hzu3", "target": "Oym3"},
	{"source": "Omx3", "target": "Ilm5"},
	{"source": "Omx3", "target": "X_r4"},
	{"source": "Aih7", "target": "Shd2"},
	{"source": "Aih7", "target": "Xod9"},
	{"source": "Kxq0", "target": "Gsa4"},
	{"source": "Aei7", "target": "Vr_1"},
	{"source": "Aei7", "target": "G_c7"},
	{"source": "Zco2", "target": "Jsu2"},
	{"source": "Uip0", "target": "Hqs9"},
	{"source": "Uip0", "target": "Fzu6"},
	{"source": "Thw9", "target": "Fze5"},
	{"source": "Thw9", "target": "Khl3"},
	{"source": "Thw9", "target": "Irx2"},
	{"source": "Bqp8", "target": "Mev3"},
	{"source": "Bqp8", "target": "Im_4"},
	{"source": "Bqp8", "target": "Xog0"},
	{"source": "Bqp8", "target": "B_g8"},
	{"source": "Bqp8", "target": "D_x9"},
	{"source": "Bqp8", "target": "Bxr6"},
	{"source": "Bqp8", "target": "Zjs0"},
	{"source": "Bqp8", "target": "Teo9"},
	{"source": "Bqp8", "target": "Fbj4"},
	{"source": "Hbj8", "target": "Dqr2"},
	{"source": "Hbj8", "target": "Qsq8"},
	{"source": "Hbj8", "target": "Pie5"},
	{"source": "Ksb1", "target": "Xef4"},
	{"source": "Ksb1", "target": "Kux7"},
	{"source": "Ndq1", "target": "Mf_8"},
	{"source": "Ndq1", "target": "Glk9"},
	{"source": "Mfg7", "target": "Ggu8"},
	{"source": "Mfg7", "target": "Pcn6"},
	{"source": "W_d9", "target": "A_d1"},
	{"source": "W_d9", "target": "Quc9"},
	{"source": "Fzs7", "target": "D_j9"},
	{"source": "Fzs7", "target": "Md_6"},
	{"source": "Dmc7", "target": "Xjg8"},
	{"source": "Dmc7", "target": "Teo9"},
	{"source": "Ojy9", "target": "Vej9"},
	{"source": "Ojy9", "target": "Avc4"},
	{"source": "Ojy9", "target": "Itn8"},
	{"source": "Ojy9", "target": "Kxq0"},
	{"source": "Ojy9", "target": "Xwl1"},
	{"source": "Ojy9", "target": "Emy6"},
	{"source": "Ojy9", "target": "G_j3"},
	{"source": "Ojy9", "target": "Ppe0"},
	{"source": "Ojy9", "target": "X_r4"},
	{"source": "Yrs7", "target": "Zdd4"},
	{"source": "Yrs7", "target": "Tzu9"},
	{"source": "Xwy7", "target": "N_t9"},
	{"source": "Ies9", "target": "Kkh8"},
	{"source": "Ies9", "target": "Jyq2"},
	{"source": "Vej9", "target": "Vib6"},
	{"source": "Avf5", "target": "Isn1"},
	{"source": "Dur5", "target": "Xju7"},
	{"source": "Dur5", "target": "Tvb2"},
	{"source": "Ouw5", "target": "Fbj4"},
	{"source": "Ouw5", "target": "Nrk3"},
	{"source": "Snm1", "target": "Qfu0"},
	{"source": "Snm1", "target": "Unv1"},
	{"source": "Snm1", "target": "Ulp3"},
	{"source": "U_b7", "target": "Ucm1"},
	{"source": "U_b7", "target": "Q_f8"},
	{"source": "Tre6", "target": "Shd2"},
	{"source": "Jti8", "target": "N_q9"},
	{"source": "Jti8", "target": "Cxj5"},
	{"source": "Rcf2", "target": "Ac_0"},
	{"source": "Rcf2", "target": "Wxa1"},
	{"source": "Px_8", "target": "Jdc6"},
	{"source": "Px_8", "target": "Jfy4"},
	{"source": "Pkb1", "target": "Po_5"},
	{"source": "Pkb1", "target": "J_u4"},
	{"source": "Mdh5", "target": "Qlw5"},
	{"source": "Mdh5", "target": "Yjz7"},
	{"source": "Ulp3", "target": "Qjb5"},
	{"source": "Ulp3", "target": "Snm1"},
]


var turns_data = [
	[
		{"source": "Ojy9", "target": "Kxq0", "num": 1},
		{"source": "Ojy9", "target": "Xwl1", "num": 2},
		{"source": "Ojy9", "target": "G_j3", "num": 3},
		{"source": "Ojy9", "target": "Ppe0", "num": 4},
	],
	[
		{"source": "Kxq0", "target": "Gsa4", "num": 1},
		{"source": "Xwl1", "target": "Qw_3", "num": 2},
		{"source": "G_j3", "target": "Rrr1", "num": 3},
		{"source": "Ppe0", "target": "Dgw1", "num": 4},
		{"source": "Ojy9", "target": "Kxq0", "num": 5},
		{"source": "Ojy9", "target": "Xwl1", "num": 6},
		{"source": "Ojy9", "target": "G_j3", "num": 7},
	],
	[
		{"source": "Gsa4", "target": "Ngn7", "num": 1},
		{"source": "Qw_3", "target": "Quc9", "num": 2},
		{"source": "Rrr1", "target": "Rby8", "num": 3},
		{"source": "Dgw1", "target": "U_p9", "num": 4},
		{"source": "Kxq0", "target": "Gsa4", "num": 5},
		{"source": "Xwl1", "target": "Qw_3", "num": 6},
		{"source": "G_j3", "target": "Rrr1", "num": 7},
		{"source": "Ojy9", "target": "Kxq0", "num": 8},
	],
	[
		{"source": "Ngn7", "target": "Yrq3", "num": 1},
		{"source": "Quc9", "target": "W_d9", "num": 2},
		{"source": "Rby8", "target": "Z_i7", "num": 3},
		{"source": "U_p9", "target": "G_c7", "num": 4},
		{"source": "Gsa4", "target": "Ngn7", "num": 5},
		{"source": "Qw_3", "target": "Quc9", "num": 6},
		{"source": "Rrr1", "target": "Rby8", "num": 7},
		{"source": "Kxq0", "target": "Gsa4", "num": 8},
		{"source": "Ojy9", "target": "Kxq0", "num": 9},
	],
	[
		{"source": "Yrq3", "target": "Cqf4", "num": 1},
		{"source": "W_d9", "target": "A_d1", "num": 2},
		{"source": "Z_i7", "target": "Fen4", "num": 3},
		{"source": "G_c7", "target": "Aei7", "num": 4},
		{"source": "Ngn7", "target": "Yrq3", "num": 5},
		{"source": "Quc9", "target": "W_d9", "num": 6},
		{"source": "Rby8", "target": "Z_i7", "num": 7},
		{"source": "Gsa4", "target": "Ngn7", "num": 8},
		{"source": "Kxq0", "target": "Gsa4", "num": 9},
		{"source": "Ojy9", "target": "Kxq0", "num": 10},
	],
	[
		{"source": "Cqf4", "target": "Zpr0", "num": 1},
		{"source": "A_d1", "target": "I_l5", "num": 2},
		{"source": "Fen4", "target": "Ter1", "num": 3},
		{"source": "Aei7", "target": "Vr_1", "num": 4},
		{"source": "Yrq3", "target": "Cqf4", "num": 5},
		{"source": "W_d9", "target": "A_d1", "num": 6},
		{"source": "Z_i7", "target": "Fen4", "num": 7},
		{"source": "Ngn7", "target": "Yrq3", "num": 8},
		{"source": "Gsa4", "target": "Ngn7", "num": 9},
		{"source": "Kxq0", "target": "Gsa4", "num": 10},
		{"source": "Ojy9", "target": "Kxq0", "num": 11},
	],
	[
		{"source": "Zpr0", "target": "Oih9", "num": 1},
		{"source": "I_l5", "target": "Kzk7", "num": 2},
		{"source": "Ter1", "target": "Mfa0", "num": 3},
		{"source": "Vr_1", "target": "Bh_7", "num": 4},
		{"source": "Cqf4", "target": "Zpr0", "num": 5},
		{"source": "A_d1", "target": "I_l5", "num": 6},
		{"source": "Fen4", "target": "Ter1", "num": 7},
		{"source": "Yrq3", "target": "Cqf4", "num": 8},
		{"source": "Ngn7", "target": "Yrq3", "num": 9},
		{"source": "Gsa4", "target": "Ngn7", "num": 10},
		{"source": "Kxq0", "target": "Gsa4", "num": 11},
	],
	[
		{"source": "Oih9", "target": "Cnf1", "num": 1},
		{"source": "Kzk7", "target": "Okb2", "num": 2},
		{"source": "Mfa0", "target": "Neu3", "num": 3},
		{"source": "Bh_7", "target": "D_v0", "num": 4},
		{"source": "Zpr0", "target": "Oih9", "num": 5},
		{"source": "I_l5", "target": "Kzk7", "num": 6},
		{"source": "Ter1", "target": "Mfa0", "num": 7},
		{"source": "Cqf4", "target": "Zpr0", "num": 8},
		{"source": "Yrq3", "target": "Cqf4", "num": 9},
		{"source": "Ngn7", "target": "Yrq3", "num": 10},
		{"source": "Gsa4", "target": "Ngn7", "num": 11},
	],
	[
		{"source": "Cnf1", "target": "Woi3", "num": 1},
		{"source": "Okb2", "target": "N_q9", "num": 2},
		{"source": "Neu3", "target": "Wmn5", "num": 3},
		{"source": "D_v0", "target": "Mbu4", "num": 4},
		{"source": "Oih9", "target": "Cnf1", "num": 5},
		{"source": "Kzk7", "target": "Okb2", "num": 6},
		{"source": "Mfa0", "target": "Neu3", "num": 7},
		{"source": "Zpr0", "target": "Oih9", "num": 8},
		{"source": "Cqf4", "target": "Zpr0", "num": 9},
		{"source": "Yrq3", "target": "Cqf4", "num": 10},
		{"source": "Ngn7", "target": "Yrq3", "num": 11},
	],
	[
		{"source": "Woi3", "target": "Xgr8", "num": 1},
		{"source": "N_q9", "target": "Jti8", "num": 2},
		{"source": "Wmn5", "target": "Oaq8", "num": 3},
		{"source": "Mbu4", "target": "Vjs2", "num": 4},
		{"source": "Cnf1", "target": "Woi3", "num": 5},
		{"source": "Okb2", "target": "N_q9", "num": 6},
		{"source": "Neu3", "target": "Wmn5", "num": 7},
		{"source": "Oih9", "target": "Cnf1", "num": 8},
		{"source": "Zpr0", "target": "Oih9", "num": 9},
		{"source": "Cqf4", "target": "Zpr0", "num": 10},
		{"source": "Yrq3", "target": "Cqf4", "num": 11},
	],
	[
		{"source": "Xgr8", "target": "Tnw2", "num": 1},
		{"source": "Jti8", "target": "Cxj5", "num": 2},
		{"source": "Oaq8", "target": "F_t5", "num": 3},
		{"source": "Vjs2", "target": "Xnu9", "num": 4},
		{"source": "Woi3", "target": "Xgr8", "num": 5},
		{"source": "N_q9", "target": "Jti8", "num": 6},
		{"source": "Wmn5", "target": "Oaq8", "num": 7},
		{"source": "Cnf1", "target": "Woi3", "num": 8},
		{"source": "Oih9", "target": "Cnf1", "num": 9},
		{"source": "Zpr0", "target": "Oih9", "num": 10},
		{"source": "Cqf4", "target": "Zpr0", "num": 11},
	],
	[
		{"source": "Tnw2", "target": "Uoe5", "num": 1},
		{"source": "Cxj5", "target": "Itb6", "num": 2},
		{"source": "F_t5", "target": "Bwf5", "num": 3},
		{"source": "Xnu9", "target": "Qjw3", "num": 4},
		{"source": "Xgr8", "target": "Tnw2", "num": 5},
		{"source": "Jti8", "target": "Cxj5", "num": 6},
		{"source": "Oaq8", "target": "F_t5", "num": 7},
		{"source": "Woi3", "target": "Xgr8", "num": 8},
		{"source": "Cnf1", "target": "Woi3", "num": 9},
		{"source": "Oih9", "target": "Cnf1", "num": 10},
		{"source": "Zpr0", "target": "Oih9", "num": 11},
	],
	[
		{"source": "Uoe5", "target": "Vlb4", "num": 1},
		{"source": "Itb6", "target": "N_l5", "num": 2},
		{"source": "Bwf5", "target": "Cm_6", "num": 3},
		{"source": "Qjw3", "target": "Hxi7", "num": 4},
		{"source": "Tnw2", "target": "Uoe5", "num": 5},
		{"source": "Cxj5", "target": "Itb6", "num": 6},
		{"source": "F_t5", "target": "Bwf5", "num": 7},
		{"source": "Xgr8", "target": "Tnw2", "num": 8},
		{"source": "Woi3", "target": "Xgr8", "num": 9},
		{"source": "Cnf1", "target": "Woi3", "num": 10},
		{"source": "Oih9", "target": "Cnf1", "num": 11},
	],
	[
		{"source": "Vlb4", "target": "S_k1", "num": 1},
		{"source": "N_l5", "target": "Jy_6", "num": 2},
		{"source": "Cm_6", "target": "Mfi7", "num": 3},
		{"source": "Hxi7", "target": "Qjb5", "num": 4},
		{"source": "Uoe5", "target": "Vlb4", "num": 5},
		{"source": "Itb6", "target": "N_l5", "num": 6},
		{"source": "Bwf5", "target": "Cm_6", "num": 7},
		{"source": "Tnw2", "target": "Uoe5", "num": 8},
		{"source": "Xgr8", "target": "Tnw2", "num": 9},
		{"source": "Woi3", "target": "Xgr8", "num": 10},
		{"source": "Cnf1", "target": "Woi3", "num": 11},
	],
	[
		{"source": "S_k1", "target": "Da_7", "num": 1},
		{"source": "Jy_6", "target": "Egv2", "num": 2},
		{"source": "Mfi7", "target": "Hx_1", "num": 3},
		{"source": "Qjb5", "target": "Ulp3", "num": 4},
		{"source": "Vlb4", "target": "S_k1", "num": 5},
		{"source": "N_l5", "target": "Jy_6", "num": 6},
		{"source": "Cm_6", "target": "Mfi7", "num": 7},
		{"source": "Uoe5", "target": "Vlb4", "num": 8},
		{"source": "Tnw2", "target": "Uoe5", "num": 9},
		{"source": "Xgr8", "target": "Tnw2", "num": 10},
		{"source": "Woi3", "target": "Xgr8", "num": 11},
	],
	[
		{"source": "Da_7", "target": "Oz_3", "num": 1},
		{"source": "Egv2", "target": "Fn_4", "num": 2},
		{"source": "Hx_1", "target": "Pwb5", "num": 3},
		{"source": "Ulp3", "target": "Snm1", "num": 4},
		{"source": "S_k1", "target": "Da_7", "num": 5},
		{"source": "Jy_6", "target": "Egv2", "num": 6},
		{"source": "Mfi7", "target": "Hx_1", "num": 7},
		{"source": "Vlb4", "target": "S_k1", "num": 8},
		{"source": "Uoe5", "target": "Vlb4", "num": 9},
		{"source": "Tnw2", "target": "Uoe5", "num": 10},
		{"source": "Xgr8", "target": "Tnw2", "num": 11},
	],
	[
		{"source": "Oz_3", "target": "Cyz9", "num": 1},
		{"source": "Fn_4", "target": "Gg_6", "num": 2},
		{"source": "Pwb5", "target": "Aai6", "num": 3},
		{"source": "Snm1", "target": "Unv1", "num": 4},
		{"source": "Da_7", "target": "Oz_3", "num": 5},
		{"source": "Egv2", "target": "Fn_4", "num": 6},
		{"source": "Hx_1", "target": "Pwb5", "num": 7},
		{"source": "S_k1", "target": "Da_7", "num": 8},
		{"source": "Vlb4", "target": "S_k1", "num": 9},
		{"source": "Uoe5", "target": "Vlb4", "num": 10},
		{"source": "Tnw2", "target": "Uoe5", "num": 11},
	],
	[
		{"source": "Cyz9", "target": "Wmo3", "num": 1},
		{"source": "Gg_6", "target": "Gmu1", "num": 2},
		{"source": "Aai6", "target": "Pdb4", "num": 3},
		{"source": "Unv1", "target": "Brq7", "num": 4},
		{"source": "Oz_3", "target": "Cyz9", "num": 5},
		{"source": "Fn_4", "target": "Gg_6", "num": 6},
		{"source": "Pwb5", "target": "Aai6", "num": 7},
		{"source": "Da_7", "target": "Oz_3", "num": 8},
		{"source": "S_k1", "target": "Da_7", "num": 9},
		{"source": "Vlb4", "target": "S_k1", "num": 10},
		{"source": "Uoe5", "target": "Vlb4", "num": 11},
	],
	[
		{"source": "Wmo3", "target": "Nuv0", "num": 1},
		{"source": "Gmu1", "target": "Aza1", "num": 2},
		{"source": "Pdb4", "target": "Nx_6", "num": 3},
		{"source": "Brq7", "target": "Mml9", "num": 4},
		{"source": "Cyz9", "target": "Wmo3", "num": 5},
		{"source": "Gg_6", "target": "Gmu1", "num": 6},
		{"source": "Aai6", "target": "Pdb4", "num": 7},
		{"source": "Oz_3", "target": "Cyz9", "num": 8},
		{"source": "Da_7", "target": "Oz_3", "num": 9},
		{"source": "S_k1", "target": "Da_7", "num": 10},
		{"source": "Vlb4", "target": "S_k1", "num": 11},
	],
	[
		{"source": "Nuv0", "target": "Jdc6", "num": 1},
		{"source": "Aza1", "target": "Xks1", "num": 2},
		{"source": "Nx_6", "target": "Gyd1", "num": 3},
		{"source": "Mml9", "target": "Rec8", "num": 4},
		{"source": "Wmo3", "target": "Nuv0", "num": 5},
		{"source": "Gmu1", "target": "Aza1", "num": 6},
		{"source": "Pdb4", "target": "Nx_6", "num": 7},
		{"source": "Cyz9", "target": "Wmo3", "num": 8},
		{"source": "Oz_3", "target": "Cyz9", "num": 9},
		{"source": "Da_7", "target": "Oz_3", "num": 10},
		{"source": "S_k1", "target": "Da_7", "num": 11},
	],
	[
		{"source": "Jdc6", "target": "Px_8", "num": 1},
		{"source": "Xks1", "target": "Pxe6", "num": 2},
		{"source": "Gyd1", "target": "Ujk6", "num": 3},
		{"source": "Rec8", "target": "Ubx4", "num": 4},
		{"source": "Nuv0", "target": "Jdc6", "num": 5},
		{"source": "Aza1", "target": "Xks1", "num": 6},
		{"source": "Nx_6", "target": "Gyd1", "num": 7},
		{"source": "Wmo3", "target": "Nuv0", "num": 8},
		{"source": "Cyz9", "target": "Wmo3", "num": 9},
		{"source": "Oz_3", "target": "Cyz9", "num": 10},
		{"source": "Da_7", "target": "Oz_3", "num": 11},
	],
	[
		{"source": "Px_8", "target": "Jfy4", "num": 1},
		{"source": "Pxe6", "target": "Hpb4", "num": 2},
		{"source": "Ujk6", "target": "Yi_9", "num": 3},
		{"source": "Ubx4", "target": "Te_1", "num": 4},
		{"source": "Jdc6", "target": "Px_8", "num": 5},
		{"source": "Xks1", "target": "Pxe6", "num": 6},
		{"source": "Gyd1", "target": "Ujk6", "num": 7},
		{"source": "Nuv0", "target": "Jdc6", "num": 8},
		{"source": "Wmo3", "target": "Nuv0", "num": 9},
		{"source": "Cyz9", "target": "Wmo3", "num": 10},
		{"source": "Oz_3", "target": "Cyz9", "num": 11},
	],
	[
		{"source": "Jfy4", "target": "Ugn1", "num": 1},
		{"source": "Hpb4", "target": "Wjm0", "num": 2},
		{"source": "Yi_9", "target": "Jij2", "num": 3},
		{"source": "Te_1", "target": "T_o9", "num": 4},
		{"source": "Px_8", "target": "Jfy4", "num": 5},
		{"source": "Pxe6", "target": "Hpb4", "num": 6},
		{"source": "Ujk6", "target": "Yi_9", "num": 7},
		{"source": "Jdc6", "target": "Px_8", "num": 8},
		{"source": "Nuv0", "target": "Jdc6", "num": 9},
		{"source": "Wmo3", "target": "Nuv0", "num": 10},
		{"source": "Cyz9", "target": "Wmo3", "num": 11},
	],
	[
		{"source": "Ugn1", "target": "Vpu2", "num": 1},
		{"source": "Wjm0", "target": "P_q7", "num": 2},
		{"source": "Jij2", "target": "Zog4", "num": 3},
		{"source": "T_o9", "target": "Ged9", "num": 4},
		{"source": "Jfy4", "target": "Ugn1", "num": 5},
		{"source": "Hpb4", "target": "Wjm0", "num": 6},
		{"source": "Yi_9", "target": "Jij2", "num": 7},
		{"source": "Px_8", "target": "Jfy4", "num": 8},
		{"source": "Jdc6", "target": "Px_8", "num": 9},
		{"source": "Nuv0", "target": "Jdc6", "num": 10},
		{"source": "Wmo3", "target": "Nuv0", "num": 11},
	],
	[
		{"source": "Vpu2", "target": "Pxq8", "num": 1},
		{"source": "P_q7", "target": "Mn_4", "num": 2},
		{"source": "Zog4", "target": "Wyr3", "num": 3},
		{"source": "Ged9", "target": "T_l2", "num": 4},
		{"source": "Ugn1", "target": "Vpu2", "num": 5},
		{"source": "Wjm0", "target": "P_q7", "num": 6},
		{"source": "Jij2", "target": "Zog4", "num": 7},
		{"source": "Jfy4", "target": "Ugn1", "num": 8},
		{"source": "Px_8", "target": "Jfy4", "num": 9},
		{"source": "Jdc6", "target": "Px_8", "num": 10},
		{"source": "Nuv0", "target": "Jdc6", "num": 11},
	],
	[
		{"source": "Pxq8", "target": "Hgt4", "num": 1},
		{"source": "Mn_4", "target": "B_c0", "num": 2},
		{"source": "Wyr3", "target": "Kvn9", "num": 3},
		{"source": "T_l2", "target": "Gvb9", "num": 4},
		{"source": "Vpu2", "target": "Pxq8", "num": 5},
		{"source": "P_q7", "target": "Mn_4", "num": 6},
		{"source": "Zog4", "target": "Wyr3", "num": 7},
		{"source": "Ugn1", "target": "Vpu2", "num": 8},
		{"source": "Jfy4", "target": "Ugn1", "num": 9},
		{"source": "Px_8", "target": "Jfy4", "num": 10},
		{"source": "Jdc6", "target": "Px_8", "num": 11},
	],
	[
		{"source": "Hgt4", "target": "Vgq8", "num": 1},
		{"source": "B_c0", "target": "Sob4", "num": 2},
		{"source": "Kvn9", "target": "Bgx2", "num": 3},
		{"source": "Gvb9", "target": "Bqj5", "num": 4},
		{"source": "Pxq8", "target": "Hgt4", "num": 5},
		{"source": "Mn_4", "target": "B_c0", "num": 6},
		{"source": "Wyr3", "target": "Kvn9", "num": 7},
		{"source": "Vpu2", "target": "Pxq8", "num": 8},
		{"source": "Ugn1", "target": "Vpu2", "num": 9},
		{"source": "Jfy4", "target": "Ugn1", "num": 10},
		{"source": "Px_8", "target": "Jfy4", "num": 11},
	],
	[
		{"source": "Vgq8", "target": "Bxr6", "num": 1},
		{"source": "Sob4", "target": "Fhi4", "num": 2},
		{"source": "Bgx2", "target": "Kaj7", "num": 3},
		{"source": "Bqj5", "target": "Amj8", "num": 4},
		{"source": "Hgt4", "target": "Vgq8", "num": 5},
		{"source": "B_c0", "target": "Sob4", "num": 6},
		{"source": "Kvn9", "target": "Bgx2", "num": 7},
		{"source": "Pxq8", "target": "Hgt4", "num": 8},
		{"source": "Vpu2", "target": "Pxq8", "num": 9},
		{"source": "Ugn1", "target": "Vpu2", "num": 10},
		{"source": "Jfy4", "target": "Ugn1", "num": 11},
	],
	[
		{"source": "Bxr6", "target": "Bqp8", "num": 1},
		{"source": "Fhi4", "target": "Uhm2", "num": 2},
		{"source": "Kaj7", "target": "Kep0", "num": 3},
		{"source": "Amj8", "target": "Teo8", "num": 4},
		{"source": "Vgq8", "target": "Bxr6", "num": 5},
		{"source": "Sob4", "target": "Fhi4", "num": 6},
		{"source": "Bgx2", "target": "Kaj7", "num": 7},
		{"source": "Hgt4", "target": "Vgq8", "num": 8},
		{"source": "Pxq8", "target": "Hgt4", "num": 9},
		{"source": "Vpu2", "target": "Pxq8", "num": 10},
		{"source": "Ugn1", "target": "Vpu2", "num": 11},
	],
	[
		{"source": "Uhm2", "target": "Opd1", "num": 2},
		{"source": "Kep0", "target": "Ibi4", "num": 3},
		{"source": "Teo8", "target": "Bko7", "num": 4},
		{"source": "Bxr6", "target": "Bqp8", "num": 5},
		{"source": "Fhi4", "target": "Uhm2", "num": 6},
		{"source": "Kaj7", "target": "Kep0", "num": 7},
		{"source": "Vgq8", "target": "Bxr6", "num": 8},
		{"source": "Hgt4", "target": "Vgq8", "num": 9},
		{"source": "Pxq8", "target": "Hgt4", "num": 10},
		{"source": "Vpu2", "target": "Pxq8", "num": 11},
	],
	[
		{"source": "Opd1", "target": "Wzd6", "num": 2},
		{"source": "Ibi4", "target": "Uzt1", "num": 3},
		{"source": "Bko7", "target": "Cxy0", "num": 4},
		{"source": "Uhm2", "target": "Opd1", "num": 6},
		{"source": "Kep0", "target": "Ibi4", "num": 7},
		{"source": "Bxr6", "target": "Bqp8", "num": 8},
		{"source": "Vgq8", "target": "Bxr6", "num": 9},
		{"source": "Hgt4", "target": "Vgq8", "num": 10},
		{"source": "Pxq8", "target": "Hgt4", "num": 11},
	],
	[
		{"source": "Wzd6", "target": "Xog0", "num": 2},
		{"source": "Uzt1", "target": "B_g8", "num": 3},
		{"source": "Cxy0", "target": "Nrr0", "num": 4},
		{"source": "Opd1", "target": "Wzd6", "num": 6},
		{"source": "Ibi4", "target": "Uzt1", "num": 7},
		{"source": "Bxr6", "target": "Bqp8", "num": 9},
		{"source": "Vgq8", "target": "Bxr6", "num": 10},
		{"source": "Hgt4", "target": "Vgq8", "num": 11},
	],
	[
		{"source": "Xog0", "target": "Bqp8", "num": 2},
		{"source": "B_g8", "target": "Bqp8", "num": 3},
		{"source": "Nrr0", "target": "Im_4", "num": 4},
		{"source": "Wzd6", "target": "Xog0", "num": 6},
		{"source": "Uzt1", "target": "B_g8", "num": 7},
		{"source": "Bxr6", "target": "Bqp8", "num": 10},
		{"source": "Vgq8", "target": "Bxr6", "num": 11},
	],
	[
		{"source": "Im_4", "target": "Bqp8", "num": 4},
		{"source": "Xog0", "target": "Bqp8", "num": 6},
		{"source": "B_g8", "target": "Bqp8", "num": 7},
		{"source": "Bxr6", "target": "Bqp8", "num": 11},
	]
]